### ISSUE TITLE
Issue with gaudi options parsing

### ISSUE THREAD

**Issue by rmatev** [ganga-devs/ganga#204] opened 2016-02-18 13:21 UTC
An issue was noticed by a few users that the newest DaVinci (v39r0p1) does not work with ganga. 

To reproduce it is enough to do:
```python
app = DaVinci(version='v39r0p1')
app.extraopts = 'from Configurables import DaVinci; DaVinci(DataType="2015")'
app.prepare()
```

I think the issue is with the way ganga tries to read the pickled option file at
https://github.com/ganga-devs/ganga/blob/0b796886d15f843d38e1a85bbb6078f0677dca93/python/GangaLHCb/Lib/Applications/PythonOptionsParser.py#L66

The problem is that gaudirun.py is not called in the correct environment (DaVinci), thus reading of the pickle fails since various classes are not available. See this little demo outside ganga:

```sh
lb-run DaVinci v39r0p1 gaudirun.py --option "from Configurables import DaVinci; DaVinci(DataType='2015')" --output test.pkl -n
# the following fails as in ganga
python -c "import cPickle; cPickle.load(file('test.pkl'))"
# this one works
lb-run DaVinci v39r0p1 python -c "import cPickle; cPickle.load(file('test.pkl'))"
```

**Comment by rmatev** [comment] 2016-02-18 13:25
Okay, what I concluded is a bit premature, as the demo at the end fails with DaVinci v38 too. There must be more to it.

**Comment by rmatev** [comment] 2016-02-18 13:26
For the record, here is the interesting part of the failure output:
```
Ganga.GangaGaudi.Lib.Applications  : INFO     Preparing DaVinci application.
Ganga.GangaGaudi.Lib.Applications  : WARNING  The 'optsfile' is not set. I hope this is OK!
Ganga.GangaLHCb.Lib.Applications   : ERROR    Cannot eval() the options file. Exception: name 'DataObjectDescriptorCollection' is not defined
Traceback (most recent call last):
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r13/install/ganga/python/GangaLHCb/Lib/Applications/PythonOptionsParser.py", line 74, in _get_opts_dict_and_pkl_string
    options = eval(opts_str)
  File "<string>", line 1, in <module>
NameError: name 'DataObjectDescriptorCollection' is not defined
Traceback (most recent call last):
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/afs/cern.ch/sw/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file PythonOptionsParser.py, line 78
<LogRecord: Ganga.GangaLHCb.Lib.Applications, 40, /afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r13/install/ganga/python/GangaLHCb/Lib/Applications/PythonOptionsParser.py, 78, " ">
None
Ganga.GangaLHCb.Lib.Applications   : ERROR    PythonOptionsParserError:
```

**Comment by rob-c** [comment] 2016-02-18 13:30
@rmatev Can this be fixed by adding the missing module to the beginning of the extra opts or do we know that Ganga is failing to parse the options within the correct environment?

**Comment by rmatev** [comment] 2016-02-18 13:43
@rob-c no, it won't work.

I understand it better now. `gaudirun.py` is not the issue. The issue (as the traceback points out) is that `eval()` runs in ganga's environment, while the supplied string looks something like
```python
{
'ConfigurableName': {'PropertyName': DataObjectDescriptorCollection()
                                   ....
                                  }
...
}
```

**Comment by rob-c** [comment] 2016-02-18 13:44
Thanks for answering my question I was in the process of confirming that there was something non string like in the dictionary

**Comment by rob-c** [comment] 2016-02-18 13:46
Does this require a change in how ganga requests this pickle to be generated or has the pickle file fundamentally changed in some way now?
The pickle in v38r0 for instance contains a valid dictionary of options.

**Comment by rmatev** [comment] 2016-02-18 13:57
I talked to @pikacic about this.

Apparently it is a glitch coming from Gaudi and is not supposed to be there. The next Gaudi version will have only plain types in the dictionary.

To make the projects released with the current Gaudi work, it seems the easiest is to make a workaround in Ganga, where you define a fake class `DataObjectDescriptorCollection`, such that the dictionary parses correctly.

**Comment by rob-c** [comment] 2016-02-18 14:03
I'd rather avoid this if possible and see if the solution can come from the DaVinci side.

I know defining this object as a plain str 'should' be good enough but this is something I'd rather avoid hard-coding into the LHCb parsing if it can be helped. I don't have the faintest clue what effect replacing all of these objects with '', and/or removing them from the dictionary would have on the jobs.

Are all of these objects even defaulting to '' safely? Does setting these options conflict with other options?

**Comment by rmatev** [comment] 2016-02-18 14:21
Are the parsed options used subsequently to construct the actual job options? From the module's docstring I gather this is only used for "extraction" of stuff:
```python
'''Uses gaudirun.py to parse the job options file to allow for easy extraction
of inputdata, outputdata and output files.'''
```

**Comment by rob-c** [comment] 2016-02-18 14:22
I'd need to investigate, it's been a while time since I fully looked at what was going on with this code.

**Comment by pikacic** [comment] 2016-02-18 14:53
As @rmatev said, the problem is that the only way to properly _eval_ the dictionary produced by `gaudirun.py`is either to import the python module defining `DataObjectDescriptorCollection` or providing a dummy callable (either a class or a function) that mimics it.
The properties that suffer from this problem are not used in any production or user job, so any value that gets there is OK (empty string is a safe and clean default).

AFAIR, this dictionary (as @rmatev suggests) is only for finding input and output files for the job, but I let you have a look.

**Comment by egede** [comment] 2016-02-18 15:16
@rmatev Can you try this trick with a fake class yourself. If it works we could inject that even at the configuration level. So in your .gangarc file have something like

`
[Configuration]
StartupGPI='class DataObjectDescriptorCollection()\n ....'
'
If that works, it would be easy to insert even into existing versions of Ganga.

**Comment by rmatev** [comment] 2016-02-18 16:12
With @pikacic we found a workaround. You can inject a function into the module where the `eval` happens. (Since GangaLHCb.Lib.Applications is quite a peculiar package, you need `sys.modules...`):
```
sys.modules["GangaLHCb.Lib.Applications.PythonOptionsParser"].DataObjectDescriptorCollection = str
```
If you do this from ganga, then `app.prepare()` works.

@egede We tried plugging this in StartupGPI, but it does not work.
```
StartupGPI = 'import sys; import GangaLHCb.Lib.Applications.PythonOptionsParser; sys.modules["GangaLHCb.Lib.Applications.PythonOptionsParser"].DataObjectDescriptorCollection = str'
```
Any further ideas how to automate this for users?

**Comment by egede** [comment] 2016-02-18 17:42
Could you define it as a global function instead?

**Comment by rmatev** [comment] 2016-02-18 18:40
In python globals are global to a module, but there is the ultimate hack (see http://stackoverflow.com/a/15959638/1630648)
```python
__builtins__.DataObjectDescriptorCollection = str
```
However, this also does not work if given to StartupGPI.

**Comment by egede** [comment] 2016-02-18 20:42
@rmatev Pity that it doesn't work through the startupGPI. Wonder if anybody has an insight to why it doesn't and if there is a clever workaround. We can insert this in an upcoming release, but the next release is locked down so it is at least 2 weeks away.

**Comment by rob-c** [comment] 2016-02-19 08:29
Hi all,
The ```import sys;...``` line appears to work when included in the users ```~/.ganga.py``` file.

@egede  As to why this works but evaluating this through the StartupGPI failes I suspect this is due to some minor detail which needs investigating.
I think I'll have a fix for this in 6.1.17 as it should only be 2 or 3 lines then this could be added to the CERN site config.

**Comment by egede** [comment] 2016-02-19 11:15
@rob-c So for 6.1.17 we might indeed just insert the `DataObjectDescriptorCollection` dummy method directly into the class. For now we can advice on the `.ganga.py` method for fixing it. The problem with StartupGPI can be solved separately.

**Comment by rob-c** [comment] 2016-02-19 11:19
OK I'll try and get a PR for 6.1.17.
As for the StartupGPI problem I'm treating it as a low priority if other solutions exist for doing what it does.

**Comment by egede** [comment] 2016-03-04 15:39
@rob-c Just a ping on this one.

**Comment by rob-c** [comment] 2016-03-04 15:41
@egede Yes, I will put in the PR after I've finished some other work I want to be certain I've not just spotted an XML related bug

**Closed** 2016-03-07 10:39 UTC
Labels: bug, LHCb
