### ISSUE TITLE
Excess directories created in `gangadir/shared/`

### ISSUE THREAD

**Issue by KonstantinSchubert** [ganga-devs/ganga#662] opened 2016-07-07 10:43 UTC
AFS has a limit of 64K file names per directory. This limit is reduced depending on the length of the file names; it is reduced to less than 22K if the file names are longer than 33 letters.

https://lists.openafs.org/pipermail/openafs-info/2002-September/005812.html

My `gangadir/shared/koschube/` directory contains `31 707` files currently, and I appear to have hit the limit.

It is no longer possible for me to create new jobs in ganga, I am getting errors like:

```
OSError: [Errno 27] File too large: '/afs/cern.ch/user/k/koschube/workspace/gangadir2/shared/koschube/conf-1e3fe559-6b5e-4db3-a9cb-25912de073ed'`
```

Please note that I had started with a completely new gangadir just a few weeks ago and that I have submitted less than 100 jobs in total (!). So this definitely isn't caused by some outrageous use case.

**Comment by KonstantinSchubert** [comment] 2016-07-07 10:50
Here is some additional evidence that the `file too large` error is caused by the number of file names being to high: https://lists.openafs.org/pipermail/openafs-info/2005-January/016196.html

**Comment by egede** [comment] 2016-07-07 10:55
This is interesting. So in principle every call to `application.prepare()`, either directly, through `j.application.prepare()` or through `j.submit()` should create a new shared area directory  if the application is not already prepared. Then, if jobs containing references to the shared areas are removed, the areas themselves should be removed. Now, if you have only ever created 100 jobs, then there should be 100 directories at most!

Did you remove the shared area as well when you say that you started on a new gangadir? If you quit Ganga with ^C, then the cleanup will not happen, but to me it seems like there is a more serious issue.

**Comment by KonstantinSchubert** [comment] 2016-07-07 11:04
> Did you remove the shared area as well when you say that you started on a new gangadir?

I am 90% sure that I created a completely empty directory when I started.

Does it create a directory for each job, or for each subjob?

Less than 100 jobs are less than 100 000 subjobs!

**Comment by egede** [comment] 2016-07-07 11:08
Can I get you to create two lists like below

```
for j in jobs:
   print j.fqid, j.application.is_prepared.name

for j in jobs:
   for js in j.subjobs:
       print j.fqid, j.application.is_prepared.name
```

and then also a file that lists all the directories in your shared directory, including their timestamp.

**Comment by KonstantinSchubert** [comment] 2016-07-07 11:10
Also, I should mention that I regularly `remove()` my jobs and I rarely keep more than 10 jobs, that is, 10K subjobs.

But the files in `gangadir/shared/koschube/` are only deleted when *exiting* ganga. This means that if my shell connection drops or an improper exit happens for another reason, those files will stick around.

 It is thus very plausible to think that the 30K subjobs of another 30 jobs are sticking around because they haven't been deleted properly.

This gives 40 K files, enough to swamp AFS.

**Comment by KonstantinSchubert** [comment] 2016-07-07 11:12
> and then also a file that lists all the directories in your shared directory, including their timestamp.

I am sorry, I have deleted the directory already  :/ I realized a minute later that this was probably a bad idea, but then it was too late.

**Comment by egede** [comment] 2016-07-07 11:14
> Less than 100 jobs are less than 100 000 subjobs! 

To me it sounds as if each subjob for some reason is creating its own shareddir. So when you start again, can you please check if each subjob gets a new directory created. Both take a look at `j.application.is_prepared.name` for the job and associated subjobs  but also look at what happens on disk.

**Comment by KonstantinSchubert** [comment] 2016-07-07 11:16
I will do that and report back.

**Comment by KonstantinSchubert** [comment] 2016-07-07 11:59
I am now in the process of submitting a new job with 943 subjobs:
```

**Comment by KonstantinSchubert** [comment] 2016-07-07 12:11
The job sumission has now proceeded to
```

**Comment by KonstantinSchubert** [comment] 2016-07-07 12:19
Here is a gist with the output of the `ls -l` command on `shared/koschube` :+1: 
https://gist.github.com/KonstantinSchubert/2d53307bc88fec74babf47fae4e8ee79

**Comment by egede** [comment] 2016-07-07 13:24
Wow! We indeed have a problem here.

**Comment by egede** [comment] 2016-07-07 13:44
OK. I reproduce the problem in a very simple setting. All the extra directories are (at least in my stripped down test) empty. Is that the same for you? If yes, you can delete them by executing

```find  ~/gangadir/shared/koschube -depth -type d -empty -delete```

as a short term solution.

**Comment by KonstantinSchubert** [comment] 2016-07-07 13:48
Indeed:

```

**Comment by egede** [comment] 2016-07-07 14:06
There is a very simple test for this. The following code creates one real and two fake directories in the `shared` area

```
j = Job()
j.prepare()
j.copy()
```

Only the first of these directories are listed in `j.application.is_prepared` of either of the two jobs. The other two directories are just ghosts. This also means that they are not reference counted and thus stay around forever.

**Comment by KonstantinSchubert** [comment] 2016-07-07 14:13
I guess the first step would be two write a unit test that checks for the right number of directories being created...

**Comment by egede** [comment] 2016-07-07 15:08
So a bit more debugging. Every time a `ShareDir` object is created an empty directory is created. This happens even if I load a job from disk and then trigger the lazy loading! The problem is the `_init` function of https://github.com/ganga-devs/ganga/blob/62c11663c2cb102c5d25330a8293af61ecb287a5/python/Ganga/GPIDev/Lib/File/File.py that each time the object is created makes a new directory. 

The solution must be that the directory is only created on demand. THis bug has been present since 2012!

**Comment by rob-c** [comment] 2016-07-07 17:32
@egede I think it may be a good idea to have a script which is callable from the GPI to clean this up for users... As for what we can do about the ShareDir, maybe we can delay construction until the name is called for the first time I think several are created and never used in the tests etc. (We may have introduced this bug in 6.1(ish) or made it worse as object construction changed to deal with the multi-threaded issues within Ganga)

**Comment by alexanderrichards** [comment] 2016-07-08 08:53
Ok So two points here.
1)
> Every time a ShareDir object is created an empty directory is created.

I think that this is expected behaviour so I would be careful to rush in and change it. Perhaps the problem is that too many sharedir objects are being created now. This ties in with your example

> j = Job()
> j.prepare()
> j.copy()

This *should* create one sharedir object at the prepare step. If three dirs are created it's presumably because three sharedir objects are created and this is the problem.

2)


> I think it may be a good idea to have a script which is callable from the GPI to clean this up for users

I'm not convinced this is a good idea as the sharedirs have a mechanism for cleaning themselves up when no-longer referenced and this suggestion would almost certainly confuse at best or break at worst this mechanism. If the mechanism is no-longer working correctly then that's what should be fixed.

**Comment by egede** [comment] 2016-07-08 09:07
@alexanderrichards Remember that when a Ganga object is copied, a deep copy is created. Hence, each time a copy of a job is created we create a new sharedir object and thus a new directory. Until any files are added into the sharedir, it is *not* counted by the shareref. The result is that users at the moment have thousand of directories that are not controlled by the sharef counter.

**Comment by alexanderrichards** [comment] 2016-07-08 09:18
The behaviour on copy should be to use the same `ShareDir` i.e. at least shallow on this attribute unless the explicit unprepareOnCopy is given in the config. In this case there should be no `ShareDir` attached. I therefore think that a straight deepcopy is not the right operation for copying Jobs. I assume that the change to enforcing a deepcopy is where this problem was introduced then.

**Comment by alexanderrichards** [comment] 2016-07-08 09:19
or at least if you do want to enforce a deep copy on job copy then the `ShareDir` logic will need to be reworked.

**Closed** 2016-07-28 06:57 UTC
Labels: bug, Core
