### ISSUE TITLE
Job is finished successfully in Dirac, but failed in Ganga. Reset backend does not help.

### ISSUE THREAD

**Issue by HannaMalygina** [ganga-devs/ganga#1602] opened 2020-03-04 10:27 UTC
Dirac portal shows "Job Finished Successfully".

Ganga says "failed".

sj.backend.reset() does not help.

Ganga also says :
WARNING ---------- error in user/extension code ----------
WARNING Traceback (most recent call last):
WARNING File "/cvmfs/ganga.cern.ch/Ganga/install/8.2.2/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 584, in updateStatus
WARNING getattr(self, state.hook)()
WARNING File "/cvmfs/ganga.cern.ch/Ganga/install/8.2.2/lib/python3.6/site-packages/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 815, in postprocess_hook
WARNING self.application.postprocess()
WARNING File "<string>", line 105, in postprocess
WARNING File "/cvmfs/ganga.cern.ch/Ganga/install/8.2.2/lib/python3.6/site-packages/ganga/GangaLHCb/Lib/Applications/XMLPostProcessor.py", line 32, in postprocess
WARNING exec(compile(xml_string, parsedXML, 'exec'), {}, metadataItems)
WARNING File "/afs/cern.ch/user/h/hmalygin/gangadir/workspace/hmalygin/LocalXML/42/54/output/__parsedxmlsummary__", line 4
WARNING events = {'output': 1000L, 'input': 0}
WARNING                                      ^
WARNING SyntaxError: invalid syntax

**Comment by mesmith75** [comment] 2020-03-04 12:44
Thanks for reporting this.

The job has finalised successfully so all your output data and log files will be in the correct place. This is a just a problem when processing the xml of the metadata so otherwise your job is fine.

It is caused by the LHCb software being python 2 but Ganga being python 3. I though we had caught all of these issues but obviously not.

**Closed as completed** 2020-03-05 03:16 UTC
