### ISSUE TITLE
Mailing list access restricted to CERN affiliated

### ISSUE THREAD

**Issue by Unode** [ganga-devs/ganga#273] opened 2016-03-04 13:50 UTC
Hi guys,

Sorry to bring this up here but I'm not really sure which other communication channels exist.
I've tried submitting a message to the mailing list and so far I didn't get a reply. In addition access to the mailing list archives is restricted to people with CERN affiliation (according to Service Desk).

So the question is, are there any other communication channels besides the CERN based mailing list?

Cheers

**Comment by drmarkwslater** [comment] 2016-03-04 13:56
Hi Renato,

Apologies for not replying to the list yet - we've been dealing with a number of issues that we've been trying to fix! Luckily that seems to be under control now so expect a reply in the next 1-2 hours!

Apologies again!

**Comment by Unode** [comment] 2016-03-04 14:01
Hi Mark,

Thanks. I wasn't sure if it was just me having a hard time or if the sent message ended up eaten by some spam filter.

**Comment by drmarkwslater** [comment] 2016-03-04 14:39
I've now replied to @Unode on the mailing list and as it stands, this issue is a duplicate of #222 so I'm closing it

**Closed by drmarkwslater** 2016-03-04 14:39 UTC

**Comment by Unode** [comment] 2016-03-04 14:46
Oh thanks, I didn't find that issue when I searched. Cheers.
