### ISSUE TITLE
report is currently very broken

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#382] opened 2016-04-15 19:23 UTC
There is a problem with the config system in the `report()` function which needs to be addressed (pref before 6.1.19 but as we have no server currently behind `gangamon.cern.ch` this function can't be used by support people anyway.

I'll post some more details and maybe a PR on Monday

**Comment by egede** [comment] 2020-02-11 22:32
Duplicate of #1023

**Closed by egede** 2020-02-11 22:32 UTC
Labels: Core, bug
