### ISSUE TITLE
No jobs updating any more, freezes when killing job

### ISSUE THREAD

**Issue by KonstantinSchubert** [ganga-devs/ganga#538] opened 2016-05-29 23:00 UTC
Dear developers,

for the past two or three days, all my subjobs are stuck in in the same state. I tried to kill and resubmit a subjob, but it doesnt't work because ganga just freezes when calling `.force_status("failed")`.

Previously I have been getting messages that some index cache was corrected (if I remember correctly).

I'll be glad to try to provide any info needed to debug this issue.

Cheers,
Konstantin

**Comment by KonstantinSchubert** [comment] 2016-05-29 23:04
Also, maybe this is related:
Calling the `jobs` command to list all jobs takes several minutes.
I have only four jobs with about 900 subjobs each.

**Comment by rob-c** [comment] 2016-05-30 16:47
@KonstantinSchubert What sort of stat are the jobs being corrected in? What version of Gaga are you using and what backend are you using?

I'm assuming that this is the latest release 6.1.20 using the Dirac backend and that your jobs are in a submitted/running state.
If this is the case I've been spending some time working on streamlining the DIRAC backend. If you're confident to install Ganga by hand please can you try #530 and report back. This branch reduces the number of potentially expensive I/O ops and such as well as reducing the total number of calls to the DIRAC backend.

The nature of the cache problems would only be a problem if your job is stuck in 'submitting' or 'completing' which it shouldn't be. If it's either of these please let me know. (or in a 'finished' or 'completed' state and you know the job is still running)

The slow response of jobs is likely caused by a lot of activity going on in your repo. Are there lots of queued tasks when you run the ```queues``` command for instance or is this empty?

**Comment by KonstantinSchubert** [comment] 2016-05-31 11:13
I am under pressure to produce some tuples at the moment, so I decided to move to a new, empty gangadir and re-start all my jobs.
I will go back to the old gangadir and try to to do this as soon as I have time.

**Comment by rob-c** [comment] 2016-05-31 11:35
@KonstantinSchubert I appreciate that there are other pressures but can you confirm at least what backend you're using?

Again, if this is DIRAC I'm debugging the monitoring loop atm and may be able to point you to an in development branch which would alleviate some problems.

**Comment by KonstantinSchubert** [comment] 2016-05-31 11:39
Sorry.
Yes, this is the latest release 6.1.20, using the DIRAC backend. 

I will try to use a development branch as soon as have a bit of time.

**Comment by rob-c** [comment] 2016-05-31 11:41
*I'd recommend #530 if you're looking for improved DIRAC performance

**Comment by rob-c** [comment] 2016-06-29 17:25
There have been substantial changes in the monitoring and code communicating with DIRAC in 6.1.21 so I'm closing this for now as I suspect most of people's issues with DIRAC have likely been addressed.

**Closed by rob-c** 2016-06-29 17:25 UTC
Labels: awaiting user input, DIRAC, LHCb
