### ISSUE TITLE
LZ Dirac Job now working

### ISSUE THREAD

**Issue by alexanderrichards** [ganga-devs/ganga#883] opened 2016-11-29 10:02 UTC
Am I doing something stupidly wrong with the new credentials system? I try the following from a fresh
```bash
$ pip install ganga
$ ganga
```

```python
[09:56:42]
Ganga In [2]: Job(backend=Dirac()).submit()
INFO     submitting job 6
INFO     job 6 status changed to "submitting"
INFO     Preparing Executable application.
INFO     Created shared directory: conf-47741432-9c2d-402b-afe6-081859985dc9
INFO     Preparing subjobs
INFO     Setting Command to be: '['echo', 'Hello World']'
INFO     submitting job 6 to Dirac backend
WARNING  Required credential [DiracProxy(group='lz', encodeDefaultProxyFileName=True)] not found in store
ERROR    Configuration of GLITE for LCG:
ERROR    File not found: /afs/cern.ch/sw/ganga/install/config/grid_env_auto.sh
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/home/local/ganga/ganga/python/Ganga/GPIDev/Adapters/IBackend.py", line 184, in master_submit
WARNING      if b.submit(sc, master_input_sandbox):
WARNING    File "/home/local/ganga/ganga/python/GangaDirac/Lib/Backends/DiracBase.py", line 256, in submit
WARNING      return self._common_submit(dirac_script_filename)
WARNING    File "/home/local/ganga/ganga/python/Ganga/GPIDev/Credentials/__init__.py", line 33, in cred_wrapped_method
WARNING      cred = credential_store.create(cred_req, create=True)
WARNING    File "/home/local/ganga/ganga/python/Ganga/GPIDev/Credentials/CredentialStore.py", line 78, in create
WARNING      cred = query.info_class(query, check_file=check_file, create=create)
WARNING    File "/home/local/ganga/ganga/python/GangaDirac/Lib/Credentials/DiracProxy.py", line 37, in __init__
WARNING      super(DiracProxyInfo, self).__init__(requirements, check_file, create)
WARNING    File "/home/local/ganga/ganga/python/Ganga/GPIDev/Credentials/VomsProxy.py", line 35, in __init__
WARNING      super(VomsProxyInfo, self).__init__(requirements, check_file, create)
WARNING    File "/home/local/ganga/ganga/python/Ganga/GPIDev/Adapters/ICredentialInfo.py", line 104, in __init__
WARNING      self.create()
WARNING    File "/home/local/ganga/ganga/python/Ganga/GPIDev/Adapters/ICredentialInfo.py", line 61, in retry_function
WARNING      return method(*args, **kwds)
WARNING    File "/home/local/ganga/ganga/python/GangaDirac/Lib/Credentials/DiracProxy.py", line 53, in create
WARNING      self.shell.env['X509_USER_PROXY'] = self.location
WARNING    File "/home/local/ganga/ganga/python/GangaDirac/Lib/Credentials/DiracProxy.py", line 68, in shell
WARNING      self._shell.env.update(getDiracEnv())
WARNING  AttributeError: 'NoneType' object has no attribute 'env'
WARNING  --------------------------------------------------
ERROR    JobManagerError: error during submit
ERROR    JobManagerError: error during submit ... reverting job 6 to the new status
INFO     job 6 status changed to "new"
ERROR    Error: JobError: Error: JobManagerError: error during submit
```

**Comment by rob-c** [comment] 2016-11-29 10:48
@alexanderrichards This is nothing to do with the credentials system. This is caused by the environment for DIRAC not being setup correctly in the config.

This should cause an exception to be raised from GetDiracEnv and I think if I'm reading this it is.
There could probably be some better handling of the error here in the credential system (A Simple try/except/raise should suffice). However this is ultimately a problem that there is no DIRAC config out of the box from the user!
(The joys of being highly specific about the exceptions you expect from a very large codebase)

**Comment by alexanderrichards** [comment] 2016-11-29 11:04
in what sense is Dirac not set up correctly? I have added it to the runtime paths and the GangaDirac package has been correctly loaded such that I can create the Dirac objects at the GPI. What do I need to do to get this working?

**Comment by rob-c** [comment] 2016-11-29 11:14
Ah... OK I thought the `None` object was coming from the Dirac env initialization.

After re-reading this more slowly I see the self._shell is not initialized here...
https://github.com/ganga-devs/ganga/blob/develop/python/GangaDirac/Lib/Credentials/DiracProxy.py#L67 Is failing and so should probably be replaced with a straight forward call to a method to replicate https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/GPIDev/Credentials/VomsProxy.py#L71 directly within the DiracProxy.

If you need me to knock together a quick PR let me know

**Comment by alexanderrichards** [comment] 2016-11-29 11:17
So upon further inspection this is caused by the fact that the `getShell()` is not returning a shell

[GridShell#L92](https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Utility/GridShell.py#L92)

This is probably due to some missing magic config that is not obvious. Relating no doubt to the lines when I start ganga
```python
WARNING  Required credential [DiracProxy(group='lz', encodeDefaultProxyFileName=True)] not found in store
ERROR    Configuration of GLITE for LCG:
ERROR    File not found: /afs/cern.ch/sw/ganga/install/config/grid_env_auto.sh
```

There used to be a config `[LCG]->Enable GLITE` or something which used to disable at least the last of these warnings but which now seems to be missing

**Comment by alexanderrichards** [comment] 2016-11-29 11:18
> After re-reading this more slowly I see the self._shell is not initialized here...
> https://github.com/ganga-devs/ganga/blob/develop/python/GangaDirac/Lib/Credentials/DiracProxy.py#L67 Is failing and so should probably be replaced with a straight forward call to a method to replicate https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/GPIDev/Credentials/VomsProxy.py#L71 directly within the DiracProxy.

Isn't it doing this anyway because it's calling the shell from the base class through super. I think the problem might lay deeper as I have outlined

**Comment by rob-c** [comment] 2016-11-29 11:21
@alexanderrichards It should probably be doing this but I'm no expert in how the inheritance and decorators may be resolved and in what order.
I still think the use of the `GridShell` is a strong weakness of this whole business.
We should probably just drop directly to a `Shell` object managed by the `DiracProxy` which makes it a __lot__ clearer what the shell is and what env it is constructed with.

**Comment by alexanderrichards** [comment] 2016-11-29 12:25
Presumably this is working in the tests. How come this works for LHCb?

**Comment by rob-c** [comment] 2016-11-29 12:34
@alexanderrichards Probably due to the differences in configuration https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Utility/GridShell.py#L69 will be invoked if the configuration and files do/don't exist as appropriate.

I strongly think the cleaner thing is to do away with the complex amounts of ifs and elses in the `GridShell` and simply manage a `Shell` object yourself in the class where it's needed it reduces complexity and makes working out what should or is going on easier.

i.e.  https://github.com/ganga-devs/ganga/blob/develop/python/GangaDirac/Lib/Credentials/DiracProxy.py#L67 should probably just read:

```
        self._shell = Shell()
```

with the appropriate import at the top of the file.

I went for inheritance to get this (or Matt did) to try and reduce the amount of `work` that is done in the derived classes but here I think it's not appropriate to think of the shell for a `DiracProxy` and a `VomsProxy` in the same way.

**Comment by alexanderrichards** [comment] 2016-11-29 12:39
Certainly when I did a quick hack fix a while ago before all this was formalised I did exactly that just set up a shell.

**Comment by alexanderrichards** [comment] 2016-11-29 12:41
Do you recall where in the config we point ganga to the Dirac setup script so that the Dirac commands have the right environment setup?

**Comment by rob-c** [comment] 2016-11-29 12:46
https://github.com/ganga-devs/ganga/blob/develop/python/GangaDirac/__init__.py#L31

Although reading:
https://github.com/ganga-devs/ganga/blob/develop/python/GangaDirac/__init__.py#L32

I suspect

**Closed** 2017-01-30 11:43 UTC
Labels: question
