### ISSUE TITLE
High CPU usage even when idle

### ISSUE THREAD

**Issue by olupton** [ganga-devs/ganga#417] opened 2016-04-27 14:48 UTC
I've noticed that even when ganga is idle (e.g. all jobs have completed, or it's just monitoring the status of a handful of jobs) it sits there consuming a lot of CPU (e.g. 65% of a "Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz" in a session open now where all jobs are either completed or failed).

I realise this isn't very helpful as-is, but is there some way of running ganga in a profiling mode so that users could provide some data about where CPU is being burnt in real-world use-cases?

**Comment by rob-c** [comment] 2016-04-27 14:56
@olupton First question, was this with develop or 6.1.18? There have been some improvements toward 6.1.19 which have significantly reduced the amount of write ops that happen which are known to be both CPU and disk intensive.

It is normally sufficient to run ganga such as:
```python -m cProfile -o myProfile.prof PATH/TO/ganga myScript.py```

for profiling which will give a file which can be fed into ```kcachegrind``` after ```pyprof2callgrind``` (I'd check the name of that latter function).

As for real world use-cases I've been profiling with 1 job with 100 subjobs, creating lists of 10k+ DiracFile objects and submitting many master jobs to/from Dirac and the Local backend. Is there anything I may have missed here?

There are some known CPU bottlenecks which are due to handling large lists (this effects amongst other things the Bookkeeping queries). This hopefully will be improved with 6.1.20 as I've a PR which addresses this and a few other tasks but I'd prefer to scrap most of the un-needed changes in the PR and start again as I think I've understood exactly where the bottleneck here is and it's that we're not passing large lists by reference we're creating destroying them on the fly which is extremely expensive.
This was spotted and fixed through profiling.

**Comment by olupton** [comment] 2016-04-27 15:20
@rob-c the specific example was the develop branch from last week sometime.

Your suggestion doesn't work for me. While this works:
`$ python ~/cmtuser/GANGA/GANGA_v601r15/install/ganga/bin/ganga --config=${HOME}/.gangarc61.test`
Adding cProfile:
`$ python -m cProfile -o myProfile.prof ~/cmtuser/GANGA/GANGA_v601r15/install/ganga/bin/ganga --config=${HOME}/.gangarc61.test`
breaks it:
```
*** Welcome to Ganga ***
Version: 6.1.18
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


Ganga.Utility.Config               : INFO     reading config file /home/lupton/cmtuser/GANGA/GANGA_v601r15/install/ganga/python/GangaLHCb/LHCb.ini
Ganga.Utility.Config               : INFO     reading config file /home/lupton/.gangarc61.test

[16:14:26]
Ganga In [1]: jobs
Ganga.Runtime.bootstrap            : ERROR    Error: name 'jobs' is not defined
Ganga.Runtime.bootstrap            : ERROR    Unknown/Unexpected ERROR!!
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/cvmfs/lhcb.cern.ch/lib/lcg/releases/Python/2.7.9.p1-df007/x86_64-slc6-gcc49-opt/lib/python2.7/cProfile.py in <module>()
----> 1 jobs

NameError: name 'jobs' is not defined
```

Your pseudo-real-world examples exclude Tasks, but perhaps if creating the profile files is easy it would be best to just encourage some heavy users to profile ganga when performing actual real-world work?

**Comment by rob-c** [comment] 2016-04-27 15:32
Ah, yes, this is the other gotcha that the env isn't passed around as much as it could be.

I'd suggest always doing:

```from Ganga.GPI import jobs; jobs```

I know it's a pain but it is possible to profile like this.


I'd advise caution before asking for lots of profiles as this can be misleading and difficult to work out what's going on. aka the profile means nothing without a way of reproducing it and a clear script highlighting the performance penalty.

Unfortunately the generated profiles atm will likely all highlight the setter method or the locking around it tbh and may not be too clear. As I've mentioned there is a significant performance bug in 6.1.20 which I'm hoping to alleviate.

After this a second very significant bottleneck is that we're generating everything we need when we construct objects rather than when they're actually needed. This can create a bottleneck.
This has tried to be addressed in #407 which delays the construction of potentially expensive objects until they're finally called. This _may_ have some perceived performance benefit but it's unclear. Although as you may see this PR although not too large causes problems with reading in from XML and deadlocks which is why this feature was dropped a while ago in favour of stability.

I suspect another a huge bottleneck in performance is in the I/O which is limited by disk access in some systems. Which will again present as a thread-lock problem although this is not strictly the case.


There is some discussion around improving our performance with Dirac atm as well but this is difficult to profile as all of the Dirac code is executed across multiple threads, although a simple code review has highlighted some obvious areas for improvement which again I'd like to get into 6.1.20 as I'm planning to spend this release working on Dirac related issues.


As for what is causing high CPU in the background this _must_ be due to the auto-save functionality which has been recently fixed in develop so unless you're certain it's still an issue today I'm a little weary of spending too much time profiling code looking for bottlenecks.

**Comment by olupton** [comment] 2016-05-03 16:08
@rob-c sorry for the delay.
The high CPU problem is certainly still present in the develop branch.
I loaded my 'real' ganga session using that branch and with cProfile and just imported `tasks` and `jobs` and printed both. It takes ~15 minutes to load and 10+ (still counting, but it already seems to have dumped the profile file) to shutdown cleanly, while in the steady state it idles at 120% CPU.

The file is attached here [myProfile.zip](https://github.com/ganga-devs/ganga/files/247264/myProfile.zip)
I am no expert at interpreting these results so I won't even try -- the largest contributions seem to be from ConfigParser and thread.lock.acquire().

**Comment by rob-c** [comment] 2016-05-03 16:23
@olupton the thread.lock.aquire will be hiding one of a few of the bugs I mentioned which I know about already and some work is needed to clean up the passing around of GangaLists and other things.
The ConfigParser is consuming a large amount of CPU if you're generating a _large_ number of Ganga objects.

How many objects are in your repos? These will all be generated on disk, which, currently is a very expensive process.

Unfortunately without knowing what is in your jobs/tasks repo I can't say why this would take so long but all I can say is that I don't observe this when testing with ~10 tasks and a few hundred jobs.

Do you have any job indexes which may be out of date? If there are jobs which haven't been created with a more recent version of Ganga then their caches may incorrect which will trigger ganga to load the whole job from disk again to regenerate the index and then it will leave.

(This _will_ happen if you're regularly moving between 6.0.44 and 6.1.xy as the caching in the former was full of bugs which have been fixed recently)

Again, without knowing _exactly_ what you're profiling I can't help too much. Are you literally printing the ```jobs``` and ```tasks``` summaries and if so how quickly do they print?

Are you seeing the ~15min taken to simply startup and print the summaries or do the summaries print in about 2-3min and the shutdown takes an extremely long time?

If the startup takes 10min then there is something breaking lazy loading and this needs looking into for 6.1.20, but if it's the shutdown that is taking 10min it's likely this is to due to the registry flushing things to disk (possibly breaking lazy loading, although possibly working as intended because your indexes are fubar).

**Comment by olupton** [comment] 2016-05-03 16:41
@rob-c I never trusted the 6.0.X -> 6.1.Y migration, so this repository has only ever been touched by 6.1.X versions, although I have jumped forward and back a bit in this series.

The repository is quite large:
```
$ ls -lSh /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/tasks/0xxx/*/data | wc -l
199

$ ls -lSh /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/jobs/*xxx/*.index | wc -l
3138
```

Certainly just typing `tasks` seems to trigger a full, extremely slow load of everything. It doesn't print any kind of summary before getting stuck loading. This doesn't get any quicker the 2nd time -- I quit the (develop branch) session that generated the profile above and re-started (again, with the develop branch), and it is still trying to print the task list now.

**Comment by olupton** [comment] 2016-05-03 17:23
I restarted the session yet again and can confirm that it is much faster to print the job summary (i.e. it prints a list of jobs when I type `jobs` "quickly") in a fresh session than it is to print the task summary.

The original issue stands -- the CPU usage hovers around 120% the entire time.

**Comment by rob-c** [comment] 2016-05-03 17:41
This sounds like a breaking of the lazy loading in the tasks codebase... I'll open an issue and ask someone to look into it. The high cpu could be due to the cpu either constructing all objects in both repos at the same time or due to slow I/O ops which can disguise as cpu bottlenecks in some systems.

**Comment by rob-c** [comment] 2016-05-03 17:41
@olupton thanks for helping spot this :+1:

**Comment by rob-c** [comment] 2016-05-03 17:45
@drmarkwslater Would you be able to look at why typing ```tasks``` seems to be loading jobs from disk?
I think modifying the current lazy loading test and requiring that calling the table method shouldn't trigger a load should be enough to test.

**Comment by olupton** [comment] 2016-05-03 17:46
Note re: CPU usage that this "never" dies off. In the past I have left an idle session open for days, and come back to find it still spinning at 120% having racked up thousands of hours of CPU time.

**Comment by rob-c** [comment] 2016-05-03 21:25
@olupton Do you ever see this when running with the task monitoring disabled? The main monitoring thread has been debugged quite a lot recently but there hasn't been the same attention paid to the tasks monitoring so it's possible that there is something here I think which can cause issues.

The use of tasks is the main difference between your use and mine and I'm simply not seeing high CPU usage on the current develop branch for myself.

**Comment by olupton** [comment] 2016-05-03 21:37
@rob-c I don't know -- do you have a recipe for turning it off without affecting anything else?

**Comment by rob-c** [comment] 2016-05-03 21:55
@olupton Could you try running off branch #439 and disable the tasks with the new config ```disableTaskMon```.
(or you could extend ```TaskLoopFrequency``` to some value like 300000000 to cause the loop to stop after 1 run but this doesn't completely separate us from the tasks running)

**Comment by olupton** [comment] 2016-05-04 15:22
@rob-c I don't know how to verify that this has worked -- is there a way to ask Ganga what monitoring is running in the background? Assuming it did work, disabling the Task monitoring has some effect but is far from the entire problem. My session now idles using around 100% CPU instead of 120%.

**Comment by rob-c** [comment] 2016-05-04 18:41
If you run with ```--no-mon``` then you get Ganga with no monitoring. (no jobs or tasks)

If your CPU usage drops as a function of this it's the monitoring of some form.

If you can run with "AutoFlusherWaitTime=99999" this will disable the Registry auto-flushing which always runs by default and could potentially be eating CPU.

If you're still experiencing high CPU with both the auto-flusher turned off and no monitoring then it would be interesting to see another profile of the code as this should kill 90% of what's going on behind the scenes.

**Comment by olupton** [comment] 2016-05-04 20:00
With `--no-mon` it drops to around 30%, AutoFlusherWaitTime=99999 didn't seem to make much difference (I added a [Registry] section to my .gangarc and put the option there).

I didn't track it closely, but it took around 15-30 mins after starting to actually drop this low. 

I ran the profiler again, you can find the results here: [myProfile.zip](https://github.com/ganga-devs/ganga/files/249482/myProfile.zip)
But presumably it's still dominated by the startup process rather than the steady-state running.

**Comment by rob-c** [comment] 2016-05-04 20:14
If you're experiencing very heavy CPU on startup are you using develop or #439 . If you're not using the latter branch then something appears to be breaking lazy loading for you in a way I've not seen before. Would you be able to attach a summary of your current jobs and tasks databases so I can try an imitate the same behaviour on a test instance.

I'm curious as to what could be using 30% CPU when ganga is idling... What sort of memory consumption are you seeing?

I'm curious as to your system config (unfortunately our report function is broken at the moment)
Could you let me know what the system is your using, if it's something dramatically different to lxplus then what OS, are you using AFS/cvmfs and are you using a VM at all?

I think it may be a good idea to build some sort of turnOnProfiling and turnOffProfiling functionality at some stage, although I've no immediate ideas how to do this and profile the whole stack.

Thanks,

Rob

**Comment by drmarkwslater** [comment] 2016-05-05 12:58
As regards Tasks, I don't think it uses lazy loading (which it should really) so it will be loading up all ~200 tasks possibly when you even start Ganga but certainly when you do `tasks`. I don't see a reason why it should trigger job loads though. I'll have to look into that.

**Comment by rob-c** [comment] 2016-05-05 13:03
@olupton Could you provide a copy of your repository directory for me to try and replicate what you're seeing locally?
@drmarkwslater Could loading a task trigger a loading of the jobs associated with it?

**Comment by drmarkwslater** [comment] 2016-05-05 13:08
@rob-c I don't believe so for `CoreTasks` but I haven't looked at the `LHCbTask` stuff for a long time and this could do that even if the Task is completed as it always polls the Tasks for updates. Have a look at `LHCbTask/Transform/Unit.update()` and see if it's querying the jobs at all.

**Comment by olupton** [comment] 2016-06-09 15:45
Hi,

Sorry for the long delay. I had some ganga-free things to see to.
I am still seeing extremely slow and high-CPU behaviour with the latest 6.1.20 (and I tried develop too).
I started with an empty repository for the study I've been doing, and the performance has deteriorated significantly as this repository has filled up.

The current repository is here: /afs/cern.ch/work/o/olupton/public/repository.tar.xz (incredibly, the compression factor is ~160...I guess indented XML is not very storage-efficient...).
If I start ganga with `--no-mon` then it idles at 30% CPU, gradually falling to 15% (when, as far as I know, it should be doing literally nothing other than waiting for my keystrokes). Typing something like `tasks` leads to a period of high CPU while it's loading, and then it gradually drops off. In `--no-mon` mode then a second `tasks` command is much faster than the first, as you'd expect.
I don't understand why there should be this tail in CPU usage from ~30% to ~15% over ~minutes of inactivity, but hey-ho.

Without `--no-mon`, the CPU usage immediately goes to 100+% and stays there. Occasionally `ps ux` shows one or more `python -` processes, which typically use around 60-70% CPU to the 100+% of the master ganga process. These are presumably monitoring processes, as they start appearing after startup even if I do not type anything at the ganga prompt.

The `jobs` and `queues` commands return quickly at the prompt, `tasks` is a little slower but soon after starting a ganga session they mostly return within a few seconds. There appears to be a correlation between the number of `python -` processes currently visible in `ps ux` and the time taken to execute a command such as `tasks`, which in some cases takes many tens of seconds.

Unfortunately, if I do something like starting a new `LHCbTask`, which creates + submits new jobs, it gets slower and slower. (using the repository I linked to then e.g. `tasks(84).run()`). Right now (3 threads submitting, none downloading output) it is [very] sluggish but bearable. In the last few days, when it has been simultaneously trying to submit new jobs and finalise submitted ones, the session has become so slow that simply running `tasks` takes many tens of minutes.

I am no ganga expert, but this apparent poor scaling with the number of threads concurrently trying to do anything perhaps suggests that they are being too aggressive with their repository access/locking?

I copied `gangadir/thread_trace.html` to http://www-pnp.physics.ox.ac.uk/~lupton/thread_trace.html as it looks like it might have useful information in it.

**Comment by rob-c** [comment] 2016-10-27 11:15
@olupton Is this behavior still present in 6.2.x?

**Comment by olupton** [comment] 2016-10-27 11:52
@rob-c short answer: I don't know, I'm not using ganga for anything just now. Up to you whether to leave this open and I'll try to update it when I next need to use ganga/tasks, or close it and I can re-open/create a new issue if turns out there has been no improvement.

**Comment by rob-c** [comment] 2016-10-27 11:53
@olupton No rush I was just wondering if I could close the issue or not given the lack of activity, I'll leave it open for now to be cautious.

**Comment by mesmith75** [comment] 2019-10-31 18:49
So I think we tracked this down in #1496 . Close this for that discussion

**Closed by mesmith75** 2019-10-31 18:49 UTC
Labels: Core, bug
