### ISSUE TITLE
runing multicores job

### ISSUE THREAD

**Issue by sabahsalih** [ganga-devs/ganga#1269] opened 2018-05-23 10:32 UTC
Dear All,  How could I submit a multicore jobs using ganga and ARC please

Many Thanks, Sabah.

**Comment by egede** [comment] 2018-05-24 08:34
@sabahsalih Do you know what the underlying syntax is for asking ARC for this. From the Ganga side, we will just pass on an option. A secondary question is if there are any multicore resources available to run on.

**Comment by sabahsalih** [comment] 2018-05-24 08:56
Dear Ulrik,
         Thank you so much for your kind reply.

I think is this

 j.backend.xRSLextras= {"count":8}
  j.backend.xRSLextras= {"count":8, "countpernode":8}

It came from


https://github.com/ganga-devs/ganga/commit/52b367862ebc7af1a81878f52ee46264437073f8
https://github.com/ganga-devs/ganga/pull/1267

Yes the Grid farm have alot of multicore resources available to run on


   Many Thanks, Sabah.

From Sabah Salih
Particle Physics Group,
The School of Physics and Astronomy,
The University of Manchester,
Schuster Laboratory,
Brunswick Street,
Manchester M13 9PL.
Tel: +44 1612754171 or  x4171
E-mail: sabah.salih@manchester.ac.uk
________________________________

**Comment by mesmith75** [comment] 2018-05-24 09:17
@sabahsalih Would it be possible to confirm that commit works as intended?

**Comment by egede** [comment] 2018-05-24 09:21
So the ability will come through #1267. So I will just close this request. As #1267 has already been merged, you can just pull the default version of Ganga from git and you will get it - or if you are running from `/cvmfs` you can use the DEV version that already has it included.

**Closed as completed by egede** 2018-05-24 09:21 UTC
Labels: duplicate, enhancement, awaiting user input

**Comment by sabahsalih** [comment] 2018-05-24 09:23
Dear Mark,
         I wil run it I feed back this afternoon.

   Many Thanks, Sabah.

From Sabah Salih
Particle Physics Group,
The School of Physics and Astronomy,
The University of Manchester,
Schuster Laboratory,
Brunswick Street,
Manchester M13 9PL.
Tel: +44 1612754171 or  x4171
E-mail: sabah.salih@manchester.ac.uk
________________________________

**Comment by sabahsalih** [comment] 2018-05-24 09:37
Dear Mark,
         I submitted the job with

     j.backend.xRSLextras= {"count":8}
    j.backend.xRSLextras= {"count":8, "countpernode":8}



   When I go to ganga
I get the following:


jobs(208)
Ganga Out [2]:
 Job (
   comment = ,
   parallel_submit = True,
   outputdir = /afs/cern.ch/user/s/sabah/gangadir/workspace/sabah/LocalXML/208/output/,
   id = 208,
   status = submitted,
   do_auto_resubmit = False,
   name = multirun8v6,
   inputdir = /afs/cern.ch/user/s/sabah/gangadir/workspace/sabah/LocalXML/208/input/,
   outputsandbox = []  ,
   inputfiles = [ LocalFile (
   namePattern = 'job-example-mgraph-qcdquadjet8v6-Delphes-multirun.sh',
   compressed = False,
   localDir = ''
 ),  LocalFile (
   namePattern = 'run_card.dat',
   compressed = False,
   localDir = ''
 ),  LocalFile (
   namePattern = 'qcdquadjet8v6.dat',
   compressed = False,
   localDir = ''
 )]  ,
   backend =    ARC (
     status = ,
     osbURI = ,
     actualCE = ce01.tier2.hep.manchester.ac.uk,
     verbose = False,
     isbURI = ,
     reason = ,
     CE = ce01.tier2.hep.manchester.ac.uk,
     id = gsiftp://ce01.tier2.hep.manchester.ac.uk:2811/jobs/R2LODm4g1fsnCshSmpWEHpUqhcrQCoABFKDmblWRDmABFKDmsG0H1n,
     queue = ,
     exitcode_arc = ,
     xRSLextras = [count, countpernode],
     workernode = ,
     jobtype = Normal,
     exitcode = ,
     requirements =      LCGRequirements (
       datarequirements = []  ,
       nodenumber = 1,
       dataaccessprotocol = [gsiftp]  ,
       cputime = 0,
       walltime = 0,
       ipconnectivity = False,
       allowedCEs = ,
       excludedCEs = ,
       other = []  ,
       memory = 0,
       software = []
     ) ,
     credential_requirements =      VomsProxy (
       group = None,
       role = None,
       identity = None,
       vo = None
     ) ,
     sandboxcache =      LCGSandboxCache (
       protocol = lcg,
       srm_token = ,
       lfc_host = prod-lfc-shared-central.cern.ch,
       se_type = srmv2,
       se_rpath = generated,
       max_try = 1,
       se = srm.cern.ch
     )
   ) ,
   subjobs = Registry Slice: jobs(208).subjobs (0 objects)
 ,
   application =    Executable (
     exe = File(name='/bin/bash',subdir='.'),
     hash = 43ee66d44809babae8f5f26a6238ab72,
     env = [],
     args = [7 Entries of type 'str'] ,
     is_prepared = ShareDir(name='conf-b462cf04-ae4b-4a10-8724-33439d0db05e',subdir='.')
   ) ,
   inputdata =None,
   metadata = {} ,
   outputfiles = []  ,
   postprocessors = [] ,
   info =    JobInfo (
     monitoring_links = []  ,
     uuid = ,
     submit_counter = 1,
     monitor =None
   ) ,
   splitter =None,
   inputsandbox = []  ,
   outputdata =None,
   time =    JobTime (
     timestamps =
         Time (UTC)   Status
- - - - - - - - - - - - - - - - - - - - -
2018/05/24 09:26:13 - new
2018/05/24 09:26:14 - submitting
2018/05/24 09:26:29 - submitted

   )
 )

[11:27:35]
Ganga In [3]:



Many Thanks, Sabah.

From Sabah Salih
Particle Physics Group,
The School of Physics and Astronomy,
The University of Manchester,
Schuster Laboratory,
Brunswick Street,
Manchester M13 9PL.
Tel: +44 1612754171 or  x4171
E-mail: sabah.salih@manchester.ac.uk
________________________________

**Comment by Sam-Tygier** [comment] 2018-05-24 13:09
Note in the above output, the xRSLextras are being passed but not displayed correctly.

`xRSLextras = [count, countpernode],`

Please see pull request #1272

**Comment by sabahsalih** [comment] 2018-05-24 16:14
Dear Mark,
         Thank you ao much. The Job is still in a submission status as the farm is full. However
 As you can see the following is an output from the batch system


Lines from the batch system

Job 303410.000 defines the following attributes:

    DiskUsage = 75
    RequestCpus = 8
    RequestDisk = DiskUsage
    RequestMemory = 16384


 As you can see ir is working.
I shall be very grateful if you could initiate a new release this week please.

   Many Thanks, Sabah.

From Sabah Salih
Particle Physics Group,
The School of Physics and Astronomy,
The University of Manchester,
Schuster Laboratory,
Brunswick Street,
Manchester M13 9PL.
Tel: +44 1612754171 or  x4171
E-mail: sabah.salih@manchester.ac.uk
________________________________

**Comment by mesmith75** [comment] 2018-05-24 16:49
@sabahsalih Thanks for letting us know it is ok. We'll push out the release tomorrow.
