### ISSUE TITLE
GangaList has no attribute "execute"

### ISSUE THREAD

**Issue by graipher** [ganga-devs/ganga#385] opened 2016-04-18 11:17 UTC
To work-around GangaList not having the attribute "append" ([GANGA-270](https://github.com/ganga-devs/ganga/issues/270), supposed to be fixed by [GANGA-179](https://github.com/ganga-devs/ganga/pull/179)), I prepared the list of postprocessors in a normal python list and added all of them in one go:
```
j = Job(name='something')
...
postprocessors = [ FileChecker(files=['stdout'], searchStrings=['INFO Application Manager Terminated successfully'], failIfFound=False, checkMaster=False) ]
if args.evtmax < 0:
  postprocessors.append(LHCbCompleteChecker())
  if all(isinstance(f, LogicalFile) for f in j.inputdata):
    postprocessors.append(LHCbBookkeepingChecker())
j.postprocessors = postprocessors[:]
```
These jobs submit and seem to run normally, but fail when trying to run the postprocessor:
```
Ganga.Core.GangaThread.WorkerThreads: ERROR Exception raised executing 'job_finalisation' in Thread 'Job 207.5 Finalizing':
Traceback (most recent call last):
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 114, in __worker_thread
    result = item.command_input.function(*these_args, **item.command_input.kwargs)
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/GangaDirac/Lib/Backends/DiracBase.py", line 666, in job_finalisation
    job.force_status('failed')
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 1919, in force_status
    raise x
JobStatusError: JobStatusError: (AttributeError("'GangaList' object has no attribute 'execute'",),) 
```
Before the error, Ganga tries 5 times to get around this, with the following, slightly more verbose, warning:
```
Ganga.Utility.logging : WARNING ---------- error in user/extension code ----------
Ganga.Utility.logging : WARNING Traceback (most recent call last):
Ganga.Utility.logging : WARNING File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 609, in updateStatus
Ganga.Utility.logging : WARNING newstatus = self.transition_update(newstatus)
Ganga.Utility.logging : WARNING File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Lib/Job/Job.py", line 648, in transition_update
Ganga.Utility.logging : WARNING passed = self.postprocessors.execute(self, new_status)
Ganga.Utility.logging : WARNING File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Adapters/IPostProcessor.py", line 111, in execute
Ganga.Utility.logging : WARNING process_result = p.execute(job, newstatus, **options)
Ganga.Utility.logging : WARNING AttributeError: 'GangaList' object has no attribute 'execute'
Ganga.Utility.logging : WARNING --------------------------------------------------
Ganga.GangaDirac.Lib.Backends : WARNING An error occured finalising job: 207.5
Ganga.GangaDirac.Lib.Backends : WARNING Attemting again (2 of 5) after 2.5-sec delay
```

**Comment by drmarkwslater** [comment] 2016-04-18 11:40
This is a problem will be fixed by #384. I'll be merging this today and it'll be in 6.1.19. As a work around, loop over the list initial list of postprocessors and call append on each separately. Thanks!

**Comment by rob-c** [comment] 2016-04-18 11:42
@graipher Thanks for submitting an issue for this, @drmarkwslater could this be caused by the default of the object not being correctly set?

**Comment by drmarkwslater** [comment] 2016-04-18 11:43
@rob-c See previous comment 😄

**Comment by rob-c** [comment] 2016-04-18 11:44
@drmarkwslater I'm curious as to how the objects appear after they've been loaded from disk again, not in the same session could be problems there?

**Comment by graipher** [comment] 2016-04-18 12:40
@drmarkwslater You mean like this:
j = Job(name='something')
...
postprocessors = [ FileChecker(files=['stdout'], searchStrings=['INFO Application Manager Terminated successfully'], failIfFound=False, checkMaster=False) ]
if args.evtmax < 0:
  postprocessors.append(LHCbCompleteChecker())
  if all(isinstance(f, LogicalFile) for f in j.inputdata):
    postprocessors.append(LHCbBookkeepingChecker())
for pp in postprocessors:
  j.postprocessors.append(pp)

Would'nt this be affected by GANGA-270 again?

**Comment by rob-c** [comment] 2016-04-18 12:43
@graipher  Adding ` ` ` without the spaces makes it clearer to read the difference between code and text.

**Comment by graipher** [comment] 2016-04-18 12:45
@rob-c Sorry, will do in the future.

**Comment by rob-c** [comment] 2016-04-18 12:47
@graipher No worries, was just a heads up so that it's easier to read :) I'm having a play with this now to test Marks fix which looks like it should work so will be in by 6.1.19

**Comment by rob-c** [comment] 2016-04-18 12:54
I do see this error occur far too much ad-infinitum on develop but it is indeed fixed by #384 and the fix works when the job has been submitted in 1 session and monitored in another.

If you see the above errors coming up a lot I would suggest forcing the job into a final status and doing the check the job by hand (a little painful I know) if you see this error coming up once every few seconds with:
``` j.force_status('failed') ```
or `completed` as appropriate.

**Closed** 2016-04-18 14:34 UTC
Labels: bug, Core

**Comment by drmarkwslater** [comment] 2016-04-18 14:36
@graipher Exactly - that should work. Basically the assignment of a list is broken but not the append of an individual PostProcessor.

**Comment by graipher** [comment] 2016-04-22 14:38
@drmarkwslater This does not work for me, see [GANGA-402](402)
