### ISSUE TITLE
automatic job resubmission broken

### ISSUE THREAD

**Issue by cjones051073** [ganga-devs/ganga#1233] opened 2018-03-01 08:50 UTC
enabling job automatic resubmission of failed (sub)jobs fails in the latest ganga versions. 

enabled with

```
 j.do_auto_resubmit = True
```

it results in

```
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.7.4/python/GangaDirac/Lib/Backends/DiracBase.py", line 457, in master_auto_resubmit
WARNING      if self._blockResubmit():
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/6.7.4/python/GangaDirac/Lib/Backends/DiracBase.py", line 616, in _blockResubmit
WARNING      raise BackendError('Dirac', 'Script for job number %s not found. Resubmission failed.' % j.fqid)
WARNING  BackendError: BackendError: Script for job number 13 not found. Resubmission failed. (Dirac backend) 
WARNING  --------------------------------------------------
ERROR    failed to resubmit job, JobManagerError: error during submit
WARNING  reverting job 13 to the submitted status
ERROR    Monitoring Error: JobManagerError: error during submit
```

Resubmitting the affected (sub)jobs by hand though works fine

```
jobs(n).subjobs(m).force_status('failed')
jobs(n).subjobs(m).resubmit()
```

**Comment by rob-c** [comment] 2018-03-01 09:12
@cjones051073 Could this be a duplicate of: https://github.com/ganga-devs/ganga/issues/1166

**Comment by cjones051073** [comment] 2018-03-07 10:30
Note, I also see the same issue in ganga 7.0.1

```
WARNING  Auto-resubmit job 69...
INFO     resubmitting job 69
INFO     job 69 status changed to "submitting"
INFO     resubmitting job 69.20 to Dirac backend
WARNING  ---------- error in user/extension code ----------
WARNING  Traceback (most recent call last):
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/7.0.1/ganga/GangaDirac/Lib/Backends/DiracBase.py", line 457, in master_auto_resubmit
WARNING      if self._blockResubmit():
WARNING    File "/cvmfs/ganga.cern.ch/Ganga/install/7.0.1/ganga/GangaDirac/Lib/Backends/DiracBase.py", line 616, in _blockResubmit
WARNING      raise BackendError('Dirac', 'Script for job number %s not found. Resubmission failed.' % j.fqid)
WARNING  BackendError: BackendError: Script for job number 69 not found. Resubmission failed. (Dirac backend) 
WARNING  --------------------------------------------------
ERROR    failed to resubmit job, JobManagerError: error during submit
ERROR    failed to resubmit job, JobManagerError: error during submit
WARNING  reverting job 69 to the submitted status
ERROR    Monitoring Error: JobManagerError: error during submit
ERROR    Monitoring Error: JobManagerError: error during submit
```

**Closed as completed** 2018-03-07 18:37 UTC
