### ISSUE TITLE
SplitByFiles(ignoremissing=False) seemingly ignored

### ISSUE THREAD

**Issue by olupton** [ganga-devs/ganga#316] opened 2016-03-15 12:23 UTC
Hi,

I just tried to submit a job with the following splitter options:
```
In [260]:jobs(4094).splitter
Out[260]: SplitByFiles (
 filesPerJob = 100 ,
 maxFiles = None ,
 bulksubmit = False ,
 ignoremissing = False
 )
```

I happened (fortunately, it could easily have been lost in the noise..) to notice:
```
WARNING  LFN: /lhcb/validation/Collision12/SWIMSTRIPPINGD02KSHH.MDST/00042039/0000/00042039_00008474_1.swimstrippingd02kshh.mdst was either unknown to DIRAC or unavailable, Ganga is ignoring it!
```
along with a few other messages along the same lines. I'm using 6.1.13 as it's the most recent release that seems somewhat usable with Tasks.

This file has a single replica, which was not available when I submitted the job, but I had hoped that having ```ignoremissing = False``` would mean that I got some kind of fatal error (or, preferably, a few subjobs that wouldn't be able to execute successfully until the site came back online).
Am I misunderstanding what the ignoremissing option is supposed to do?
It seems that if I hadn't spotted the warning then everything could have "succeeded" despite some fraction of the input data having been ignored, which is not good.

**Comment by rob-c** [comment] 2016-03-15 12:26
@olupton If you're able I'd advice using the ```bugfix/LHCbfixes``` branch from github if you're able as this should have most of the fixes from 6.1.17 as well as 'working' tasks. I think I fixed something relating to this a few releases ago but I couldn't say when without doing some digging.

**Comment by olupton** [comment] 2016-03-15 13:35
@rob-c I am trying now. I didn't want to because this is some work that I really need to get done, and the github versions don't have a great stability record, however 6.1.13 seemed to struggle so much with scalability (as well as the above issue) that I don't have much choice.

I am trying to load my 6.1.13 repository with the head of the ```bugfix/LHCbfixes``` branch, but it has been apparently stuck for several minutes now. ```lsof``` shows:

```
[lupton@pplxint8 ~]$ lsof -p 465 2>/dev/null | grep akepahome
python  465 lupton    3u   REG 1631,703664        0 144115342090772301 /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/sessions/global_lock
python  465 lupton    5u   REG 1631,703664        0 144115342090772301 /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/sessions/global_lock
python  465 lupton    6u   REG 1631,703664        0 144115342090772301 /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/sessions/global_lock
python  465 lupton    7u   REG 1631,703664        0 144115342090772301 /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/sessions/global_lock
python  465 lupton    8u   REG 1631,703664        0 144115342090772301 /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/sessions/global_lock
python  465 lupton    9u   REG 1631,703664        0 144115342090772301 /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/sessions/global_lock
python  465 lupton   11u   REG 1631,703664        0 144115342090772301 /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/sessions/global_lock
python  465 lupton   12u   REG 1631,703664        0 144115342090772301 /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/sessions/global_lock
python  465 lupton   13u   REG 1631,703664        0 144115342090772301 /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/sessions/global_lock
python  465 lupton   14r   REG 1631,703664   350738 144115377071258976 /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/tasks/0xxx/42/data
```

Where the last file is a very modest 343k:

```
[lupton@pplxint8 ~]$ ls -lh /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/tasks/0xxx/42/data
-rw-r--r-- 1 lupton pp-lhcb 343K Mar 15 13:06 /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/tasks/0xxx/42/data
```

It appears to be some kind of locking problem (?):

```
[lupton@pplxint8 ~]$ strace -p 465
Process 465 attached
futex(0x26f3af0, FUTEX_WAIT_PRIVATE, 0, NULL
```

All I have done is open a new session and type ```tasks```.

What can I do? This is a "production" session that I really don't want to corrupt by force killing ganga and so on.

**Comment by olupton** [comment] 2016-03-15 13:46
I noticed it's doing some things in the background. e.g. lsof sometimes shows another file:
``` /data/lhcb/users/lupton/akepahome/olupton/gangadir61/repository/olupton/LocalXML/6.0/jobs/4xxx/4093/data.new
```
where I think (but can't be sure because the session won't let me do anything...) that job 4093 plausibly has some running subjobs. 
Also child processes are occasionally spawned:

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
lupton     465 76.3  0.2 2910112 171032 pts/57 Sl+  13:25  15:22 python /home/lupton/cmtuser/GANGA/GANGA_v601r15/install/ganga/bin/ganga --config=/home/lupton/.gangarc61
lupton   15259 54.7  0.0 307900 29624 ?        Rsl  13:45   0:02 python -
```
which lsof shows having the same set of open files.
The ganga prompt is still frozen (Ctrl-C doesn't work).

**Comment by olupton** [comment] 2016-03-15 13:46
Sorry, I didn't mean to close it but apparently can't reopen.

**Comment by olupton** [comment] 2016-03-17 07:45
Drifting away from the original topic, but I tried the head of ```bugfix/LHCbfixes``` again this morning with the same result: just typing ```tasks``` leads to a complete lock-up.
The repository I'm trying to open is ~2.5G
```
[lupton@pplxint8 /data/lhcb/users/lupton/akepahome/olupton/gangadir61]$ du -sh repository/
2.5G 	repository/
```
and contains 134 tasks (1 of which is running) and 2912 master jobs (2 of which are running).

6.1.13 doesn't have the hard lock-up, but does struggle with multiple threads (e.g. two parallel submits are much slower than two sequential ones). If I set the number of worker threads to 1 then it seems to get on with things.

**Comment by mesmith75** [comment] 2016-06-13 13:18
Returning to the original problem, I was unable to reproduce it on a quick test, albeit with a made-up LFN rather than one in the catalogue. I got the warning followed by an error, more warnings and the job didn't submit.

**Comment by rob-c** [comment] 2016-06-14 14:06
@mesmith75 Are you able to correctly submit a job with working LFN with a single bad (made-up) LFN added into the mix? If so I think we can close this as fixed.

**Comment by mesmith75** [comment] 2016-06-14 15:10
If I have one bad LFN in a list of otherwise ok LFNs and ignoremissing=False then the job doesn't submit as expected.
If ignoremissing = True then this job submits fine but with the warning about the bad LFN.

**Comment by alexanderrichards** [comment] 2016-06-14 15:30
this sounds like the expected behaviour has been fixed already. I'll close this issue then and we can re-open it if we or @olupton spots this again. thanks for checking @mesmith75

**Closed by alexanderrichards** 2016-06-14 15:30 UTC
Labels: bug, DIRAC, LHCb
