### ISSUE TITLE
FileChecker has not attribute 'order'

### ISSUE THREAD

**Issue by graipher** [ganga-devs/ganga#402] opened 2016-04-22 14:38 UTC
While trying to implement the workaround mentioned by @drmarkwslater in [GANGA-385](385), I am running into this error with FileChecker:

```python
Traceback (most recent call last):
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/bin/ganga", line 69, in <module>
    Ganga.Runtime._prog.run()
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/Runtime/bootstrap.py", line 1234, in run
    execfile(script, local_ns)
  File "./submit.py", line 105, in <module>
    j.postprocessors.append(pp)
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Adapters/IPostProcessor.py", line 89, in append
    self.process_objects, key=lambda process: process.order)
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Adapters/IPostProcessor.py", line 89, in <lambda>
    self.process_objects, key=lambda process: process.order)
  File "/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v601r18/install/ganga/python/Ganga/GPIDev/Base/Proxy.py", line 1016, in _getattribute
    returnable = GPIProxyObject.__getattribute__(self, name)
AttributeError: 'FileChecker' object has no attribute 'order'
```

Corresponding code in my submission script:
```python
postprocessors = [
        FileChecker(files=['stdout'], searchStrings=['INFO Application Manager Terminated successfully'], failIfFound=False, checkMaster=False)]
if args.evtmax < 0:
    postprocessors.append(LHCbCompleteChecker())
    if all(isinstance(f, LogicalFile) for f in j.inputdata):
        postprocessors.append(LHCbBookkeepingChecker())
for pp in postprocessors:
        j.postprocessors.append(pp)
```

**Comment by milliams** [comment] 2016-04-22 14:40
This is being caused by a proxied object getting though the proxy layer. It should be fixed with #393 but we'll have to run some tests.

**Comment by graipher** [comment] 2016-04-22 14:43
OK, thanks. 
BTW when is 6.19 expected to be released/when can I at least easily test it with SetupProject Ganga --dev v601r19?

**Comment by rob-c** [comment] 2016-04-22 14:51
Due to not wanting to have to support branches in various different stages of development we're not providing Ganga in the dev area between releases for every release.
To install it yourself from git see: http://ganga.readthedocs.org/en/latest/UserGuide/InstallAndBasicUsage.html

If you need some help feel free to send a pm after trying to install it

**Comment by milliams** [comment] 2016-05-11 10:37
@graipher I am unable to reproduce this in 6.1.19. Do you have a minimal reproducible example which I can test against? `LHCbCompleteChecker` and `LHCbBookkeepingChecker` are not Ganga classes.

**Comment by graipher** [comment] 2016-05-11 10:46
Hey @milliams,
I can also not reproduce this anymore in 6.1.19, with these custom classes.
Maybe it was fixed by whatever fixed #270?

**Comment by graipher** [comment] 2016-05-11 10:51
Also, before already FileChecker (which is an official Ganga class, right?) was failing with this error, so deleting everything after that should produce a reproducible example (failing in 6.1.18, succeeding in 6.1.19).

**Comment by milliams** [comment] 2016-05-11 11:00
@graipher Cheers. Indeed I can reproduce this in 6.1.17 and it is fixed in at least `develop` and apparently in `6.1.19`.

**Closed by milliams** 2016-05-11 11:00 UTC
Labels: bug
