### ISSUE TITLE
Subjob marked as dirty makes all subjobs get flushed

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#360] opened 2016-04-07 09:54 UTC
At present, according to `flush` in SubJobXMLList.py, if the parent job is marked as dirty (which it will be if any subjobs change) then ALL the subjobs get flushed. This can be an expensive operation if there are a lot of subjobs which could make the monitoring go very slowly.

Ideally, it should only flush dirty subjobs, not all of them.

**Comment by egede** [comment] 2016-04-07 09:59
Just to underline that it is suspected that this issue could be the cause of monitoring slowing down in LHCb.

**Comment by rob-c** [comment] 2016-04-07 10:20
I know we mark Job objects as not dirty after a flush but I don't think we correctly address marking all objects within the schema as clean afterwards, just the parent. Can we improve the ```_setFlushed``` method so we do things in future like what attributes are triggering most objects to become dirty.

**Comment by egede** [comment] 2016-04-07 10:31
> Can we improve the _setFlushed method so we do things in future like what attributes are triggering most objects to become dirty.

@rob-c I do not understand what you mean here? You want to make sure that we go in and mark the subjobs as not dirty after flushing or do you want to collect statistics on what is dirty in jobs?

**Comment by rob-c** [comment] 2016-04-07 10:59
@egede I want to be sure that we mark all dirty objects as clean after flushing. Atm an object and all of it's parents are marked dirty with a ```_setDirty```. We only mark the root object clean after flushing. I would like to make sure we mark all objects hanging off the root as clean.

In future we can think about looking at which objects are triggering this if we feel that objects are excessively dirty when they shouldn't be changing, but atm all objects are all dirty under the parent regardless of if they were dirty 5min ago or 5 days ago.

**Comment by egede** [comment] 2016-04-07 11:04
@rob-c OK. Essential thing is indeed to make sure that everything that is flushed is actually marked clean afterwards.

**Comment by rob-c** [comment] 2016-04-11 16:21
Fixed by #367

**Closed by rob-c** 2016-04-11 16:21 UTC
Labels: Core, enhancement
