### ISSUE TITLE
ganga 7.1.14 performance problems

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#1470] opened 2019-05-25 14:01 UTC
This is CentOS 7 / x86_64 with its default python 2.7.5 and the Slurm batch system.

I am running a single task with something like 70 transforms with 600\+ Slurm jobs.

1. The ganga 7.1.14 executable constantly eats / uses 100% CPU (for no reason as it actually waits for 25 already submitted jobs now). I think it began right at startup. In the beginning, ganga was submitting around 600 Slurm jobs and I think that this was really very slow (i.e. it took much more time than with previous ganga versions). UPDATE: the "task" completed and ganga was still using 100% CPU.

2. The "tasks.table()" command needs at least 3 minutes to print its output (again, ganga does nothing, just waiting for submitted jobs). UPDATE: the "task" completed it it still needed 3 to 4 minutes.

3. The "jobs" command needs at least 25 seconds to print its output (again, ganga does nothing, just waiting for submitted jobs). UPDATE: the "task" completed it it still needed at least 25 seconds.

4. I do not get "INFO" lines on the screen, when I want them. In previous versions (including ganga-7.1.12), when I pressed "enter", ganga "flushed" its logger output to the screen. This no longer works. It seems to me that ganga collects all messages in the "\_logfile" (100kB) and once its size is exceeded, it renames it into "\_logfile.1" and again collects all messages in the new "\_logfile". First when this new "\_logfile" file exceeds it size, ganga "flushes" the existing "\_logfile.1" to the screen, then it "rotates" log files and the whole process of collecting messages continues. So, what I get on the screen is at least 200kB old. How can I get the "enter" working again? Or maybe there is some magic command which triggers the "flushing"? I known I can reduce the "\_logfile_size" size but, is this the right thing to do? I will always see messages which are at least "2 * \_logfile_size" old. I could maybe disable the "\_interactive_cache" but, I am not sure if this is really a good idea either (I never tried it). Note: all "[Logging]" settings are unchanged with respect to the old versions like ganga-7.1.12 (and even ganga-6.0.44), where the "flushing" was working fine. UPDATE: the "task" completed but the logger was not "flushed". First when I executed "exit()" (it needed something like 2 minutes to terminate), I got all collected messages (from the "\_logfile.1" and then the "\_logfile") printed to the screen.

**Comment by egede** [comment] 2019-05-26 23:56
We have not had any other similar reports and it is very difficult to deal with this kind of very generic bug report. Is the behaviour a regression from a previous series 7 release? If you switch back to 7.1.12, do you see problems 1-3 disappear? For problem 4, @mesmith75 should comment. There has been some changes in this area, but nothing that should cause your reported behaviour.

**Comment by mesmith75** [comment] 2019-05-27 21:13
For no. 4, yes this is a deliberate change. Users were complaining about INFO appearing whilst typing code - for some reason IPython redraws the prompt when a user is typing. Therefore we had to move the INFO flushing to be when a cell executed. This is at the request of 99% of our users. I hope that when we upgrade to python 3 and IPython 6 we can resolve this a little better.

For the others, I am not sure what to suggest. I tried a fresh install and submitted 100 jobs and everything is as quick as it ever has been. If you have lots of jobs running then things will likely slow down due to the large I/O when reading/writing to disk.

**Comment by JacekHoleczek** [comment] 2019-05-28 12:30
Many thanks for your comments.

I cannot really re-run the whole task (it takes too much time and resources).

I don't really believe that the problem is related to some "large I/O". Note that I wrote the report when all the first 600 jobs (from some 20 transforms ran in parallel) finished and there were just some 25 submitted jobs (from some next 5 transforms ran in parallel) waiting in the batch queue and then the "UPDATE" after the whole task finished ... and ganga was eating 100 % CPU all the time.

I now ran a minimal trial task with the first step with 20 jobs from 2 transforms (and the second step with several jobs from several transforms).

Right after startup, ganga was using around 7 % CPU. After it submitted all 20 jobs, it was using something like 15 % CPU time and it stayed at this number (or maybe it even increased by 2 or 3 percent after the second step) even after the task completed.
I did not get any single "INFO" printed. I guess the problem was that the total "\_logfile" was below 100kB. I tried to press "enter", execute "tasks.table()", "jobs", "1+1" but the logger was never "flushed" (I got all messages printed first when I executed "exit()").

So, I set "\_interactive\_cache \= False" and re-run the minimal trial task. This time, all "INFO" messages were printed immediately. The CPU usage, however, was again at around 15 - 17 %, even after the task completed.
I also noticed that pressing any key (or maybe it's only the "enter") will destroy the last printed "INFO" message line (or maybe two lines) as, in that place on the screen, one gets the two new "\[HH\:MM\:SS\] and "Ganga In \[\.\.\.\]\:" prompt lines (note that every single key stroke automatically updates the first "\[HH\:MM\:SS\]" line).

I decided to run a slightly less minimal trial task with the first step with 40 jobs from 4 transforms (so, twice as many as in the previous "minimal trials" which also adds 2 transforms to the second step). The CPU usage increased (from around 15 % for the previous "minimal trials") to something like 24 % (and it stays at this number also after the task completed). I can also clearly see that the output from "tasks.table()" is really "delayed" by at least 3 seconds now ("jobs" needs around 1 second).

So, if my "whole task" has 21 top level (first step) transforms, then ... 7 % "initial CPU usage" + 21 * 4.5 % "per top level transform CPU usage" = 101.5 % "total" CPU. Does this make sense?

I'm afraid I forgot to warn you that, when I say "task", I really mean "[ND280Task](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaND280/Tasks/ND280Task.py)" and, when I say "transform", I really mean "[ND280Transform](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaND280/Tasks/ND280Transform.py)" ("jobs" in the first step are "[RecoPlusVFT](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaND280/ND280RecoValidation/RecoPlusVFT.py)" and in the second step "[VFT_make_ana](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaND280/ND280RecoValidation/VFT_make_ana.py)"). If you do not see such problems in your own tests then they may be related to "[GangaND280](https://github.com/ganga-devs/ganga/tree/develop/ganga/GangaND280)" only (so, I'm afraid you will not be able to run my trials). Could you, please, have a look at the relevant python files and tell me if you see anything "suspicious" or "wrong"?

**Comment by alexanderrichards** [comment] 2019-07-18 10:16
I wonder if running something like [profile](https://docs.python.org/2/library/profile.html) would help us understand what's happening? Would it be possible for you to try with a simple job @JacekHoleczek

**Comment by JacekHoleczek** [comment] 2019-07-18 11:06
It seems I do have "cProfile" and "profile" available (on the headnode of the batch cluster) so, I will try to run the "40 jobs from 4 first step transforms" trial using:
`stdbuf -i0 -o0 -e0 python -m cProfile /full/path/to/ganga-7.1.14/bin/ganga 2>&1 | tee cProfile.out.txt`

**Comment by JacekHoleczek** [comment] 2019-07-19 12:46
Here's the (gzipped) full "output" from the trial: [cProfile.4.40.out.txt.gz](https://github.com/ganga-devs/ganga/files/3411114/cProfile.4.40.out.txt.gz)

**Comment by egede** [comment] 2019-07-22 02:23
Frmatted in a spreadsheet.
[cProfile.4.40.out.xlsx](https://github.com/ganga-devs/ganga/files/3415412/cProfile.4.40.out.xlsx)

Do I understand from this that the `raw_input` function is using all the time? Is this related to recent changes made in how we deal with the prompt?

**Comment by egede** [comment] 2019-07-22 05:30
Two small tests that maybe can be carried out to see if they make the CPU issue go away.

1. Start `ganga` with the `--very-quiet` option. This will remove all output from the logger apart from `CRITICAL` messages. It will show if it is somehow related to something going on with a large number of messages.
2. Try to run `ganga` without using `ipython`. You can do this by importing `ganga` into a `python` session instead like in the minimal example below.

```
from ganga.ganga import ganga
ganga.runMonitoring()
j = ganga.Job()
j.submit()
```

**Comment by egede** [comment] 2019-07-22 05:53
Looking again at the original cProfile, I am confused. The total time reported by `raw_input` is 3200 seconds, which seems more or less just to be the time between starting and stopping `ganga` (like 09:16 to 10:08). So does cProfile just report wallclock time and not CPU time. If yes, it makes perfect sense that raw_input spent about 3200 seconds waiting for a prompt. Looking at https://stackoverflow.com/questions/653419/how-can-i-profile-a-multithread-program-in-python it seems like cProfile is only looking at the main thread which from this seems to do nothing unusual. So likely the problem is caused by a background thread. What happens if you after the task has completed type `queues`. You should see something like

```
Ganga In [1]: queues                                                                                                                                                                                               
Ganga Out [1]: 
                        Ganga user threads:                         |             Ganga monitoring threads:             
                        ------------------                          |              ------------------------             
Name                       Command                    Timeout       | Name                       Command                      Timeout   
----                       -------                    -------       | ----                       -------                      -------   
User_Worker_0            idle                       N/A             | Ganga_Worker_0           idle                         N/A       
User_Worker_1            idle                       N/A             | Ganga_Worker_1           idle                         N/A       
User_Worker_2            idle                       N/A             | Ganga_Worker_2           idle                         N/A       
User_Worker_3            idle                       N/A             | Ganga_Worker_3           idle                         N/A       
User_Worker_4            idle                       N/A             | Ganga_Worker_4           idle                         N/A       

Ganga user queue:
----------------
[]
Ganga monitoring queue:
----------------------
[]
```

so everything should report idle. Or if you execute `disableMonitoring()` after the task has finished, does the CPU usage drop to zero?

**Comment by JacekHoleczek** [comment] 2019-07-29 11:33
As I write in my previous posts, it seems that the ganga's CPU usage is "proportional" to the number of the top level (first step) transforms in a task. So, if each such a transform creates a separate thread and the cProfile does not take them into account at all then it will not really help in debugging the problem.

1. I ran the small `--very-quiet` trial ... here's the (gzipped) full "output" from it: 
[cProfile.4.40.out.txt.gz](https://github.com/ganga-devs/ganga/files/3441814/cProfile.4.40.out.txt.gz)
   As you can see, the CPU usage did NOT change with respect to the previous trial (well, even without the `--very-quiet` option, the screen output was rather small, just the usual Ganga messages for each job).
   When I execute `disableMonitoring()`, the CPU usage immediately drops from 24% to 6% (which is equal to the "initial" ganga's CPU usage).
   The output from `queues` is exactly as expected (both, before and after `disableMonitoring()`).

2. I was not able to run Ganga with "python" (i.e. without using "ganga" script).
   As soon as I execute `from ganga.ganga import ganga`, the python's CPU usage increases (from almost 0%) to around 6% (and it stays at this number all the time). I get the line "INFO reading config file \/\.\.\.\/\.gangarc" repeated 5 times (this does not happen when one runs the standard "ganga" script). Executing `ganga.runMonitoring()` returns `True` (if that matters).
   I needed to modify all Ganga related calls in my script, prepending them with "ganga.". I can now `execfile('RunFullValidation.py')` without any error but when I then execute `tsk.run()`, nothing happens (`tsk = ganga.ND280Task()`, if that matters). No error is reported but no job is started.
   So, I guess I need some guidance how to proceed here (and, if possible, how can I get rid of these superfluous "ganga." strings, so that, e.g., I could simply call `runMonitoring()` and NOT `ganga.runMonitoring()`).

**Comment by egede** [comment] 2019-07-30 00:19
From the above, it seems to me that the problem is related to the monitoring of the Tasks. I have tried to look a bit at the code for that. There is a specific thread started for this that executes the function 

https://github.com/ganga-devs/ganga/blob/d4fa1cce3cf5d4d8d8a3fdc990cfdf1d82b41ef4/ganga/GangaCore/GPIDev/Lib/Tasks/TaskRegistry.py#L53

Apart from the slightly aggressive loop at the end of the monitoring cycle (loops every 0.01 seconds), it seems fine. The thread then calls the `update` method on each task in

https://github.com/ganga-devs/ganga/blob/d4fa1cce3cf5d4d8d8a3fdc990cfdf1d82b41ef4/ganga/GangaCore/GPIDev/Lib/Tasks/ITask.py#L86
which in turn calls update on all its transforms that then goes and calls update on all its units

https://github.com/ganga-devs/ganga/blob/d4fa1cce3cf5d4d8d8a3fdc990cfdf1d82b41ef4/ganga/GangaCore/GPIDev/Lib/Tasks/IUnit.py#L176

Clearly this tree like behaviour can lead to a very large number of call to the update method at the Unit level. At the end of this, the thread started at the beginning sleeps for a bit (default 1 minute) and then start over.

From this, I see two causes of the CPU usage. Either it is caused by the task monitoring itself, or it is caused by the monitoring of the jobs associated with the tasks. Can you try to run two tests

1. Set `disableTaskMon = False` in the configuration? This will keep the job monitoring running but will disable the task monitoring.
2. Set `ForceTaskMonitoring = True` and call `disableMonitoring()` inside Ganga. This will do the opposite (keep the Task monitoring going but disable the job monitoring.

My hope is that the tests will give us a clue to where to look next. How many jobs are overall involved in one of your active tasks?

**Comment by JacekHoleczek** [comment] 2019-07-30 06:27
You can see the full output from `jobs` and `tasks.table()` in both attached files (in my previous posts).

Concerning the new test `1.` ... in the configuration file, I can see a commented out line `#disableTaskMon = False` which seem to suggest that "False" is the default setting or is it not?

Concerning the new test `2.` ... should I also set `disableTaskMon = False`, or should I leave this line commented out?

**Comment by egede** [comment] 2019-07-30 06:37
Sorry, for task one, I meant of course setting it to `True`. Remember to take away the `#` from the line. For Task 2, leave `disableTaskMon` as is (so `False`).

**Comment by JacekHoleczek** [comment] 2019-07-30 09:37
1. The `disableTaskMon = True` trial ...
   The "initial" ganga's CPU usage is around 6% and it seems to stay at around 6 - 10 % all the time.
   Unfortunately, after `tsk.run()`, NO JOB is started ... I waited 15 minutes and NOTHING happened.
   The `jobs` output is completely empty.
   In the `tasks.table()` output, I can see that all transforms are "running".
   The `queues` output looks like always ("idle").

2. The `ForceTaskMonitoring = True` trial ...
   The "initial" ganga's CPU usage is around 6%.
   The CPU usage increases when Ganga is submitting jobs but, once all 40 jobs from the 4 "first step" transforms are submitted, it returns to around 6% and every minute it increases to 100% for something like 5 to 10 seconds.
   After all 40 (SLURM) jobs are finished (no errors reported), Ganga does nothing.
   I waited for something like 40 minutes additionally and still nothing.
   That means that no "second step" transform is run (i.e. no "second step" jobs are submitted).
   In the `jobs` output, I can see that all 40 jobs as "submitted" (to "Slurm").
   In the `tasks.table()` output, I can see that all transforms are "running".
   The `queues` output looks like always ("idle").

I do no attach here any "cProfile" output (for these two above trials) but I do have them saved so, if you want them, let me know.

**Comment by egede** [comment] 2019-07-31 00:55
Hmm, I can see why this happens, but it did not teach us too much. So we know now that the cause of the high CPU usage is from the monitoring threads. That the `TaskMonitoring` thread is using 100% CPU for 5-6 seconds (when there are only very few jobs in the system is a worry. If that scales with the number of jobs, then you could see that he idle period of one minute could be far between. If you try to insert some debugging information in the monitoring code for the Task, we might learn something. See my overview of the `update` methods above.

**Comment by JacekHoleczek** [comment] 2019-07-31 08:36
What "debugging information" should I add into these "\_thread\_main" and "update" methods?

**Comment by egede** [comment] 2019-08-01 00:09
As a better idea, I have instrumented a version of Ganga to give profile information for the threads. Can you try to install Ganga from https://github.com/ganga-devs/ganga/tree/CProfileThreads and give it a go. Just run it as normal (`cProfile` s enabled internally for the threads). It will print the profile at the end on `stdout`, so just post that back. To install from the branch, you can do

```
pip install git+https://github.com/ganga-devs/ganga.git@CProfileThreads
```

**Comment by JacekHoleczek** [comment] 2019-08-01 15:13
Many thanks for your help.

Here's the (gzipped) full "output" from the new trial: [CProfileThreads.4.40.out.txt.gz](https://github.com/ganga-devs/ganga/files/3457379/CProfileThreads.4.40.out.txt.gz)

**Comment by egede** [comment] 2019-08-02 04:59
OK, that didn't work as I did not realise that something special was required for static methods. So lets us try again. I now use the profiling method that @ishanrai05 implemented. So do

```
pip install git+https://github.com/ganga-devs/ganga.git@ProfileMonitoring
```
Then run `ganga` with

```
ganga -o'[Configuration]Profile_CPU=True'
```
and finally pack up in a tarball all the files created under `gangadir/logs/cpu_profile`. In particular, it is the `TaskRegistry-_thread_main` and the different `updateMonitoringInformation` files that I am interested in.

**Comment by JacekHoleczek** [comment] 2019-08-02 08:10
Full "logs" from the new trial: [gangadir.logs.4.40.ganga-7.1.14.2019.08.02.06.29.tar.gz](https://github.com/ganga-devs/ganga/files/3460210/gangadir.logs.4.40.ganga-7.1.14.2019.08.02.06.29.tar.gz)

The "initial" ganga's CPU usage was around 25%.
After my task was `run()`, it increased to 50 - 70% ("oscillating") and stayed in this range also after the task was "completed".

**Comment by egede** [comment] 2019-08-05 23:46
So I am getting some understanding of this. I managed to get the profiling to work for all threads and I looked at a simple Ganga session that does absolutely nothing. That takes up 20% of CPU time, by just keeping the threads alive. Look at tables below.

First just CPU time used.

```
Tue Aug  6 09:04:44 2019    pstats

         3025011165 function calls (3045501047 primitive calls) in 18608.766 seconds

   Ordered by: internal time
   List reduced from 2552 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
111672296/111672382 5302.618    0.000 5302.619    0.000 time:0(sleep)
15955981/15956009 3455.435    0.000 10966.966    0.001 threading.py:309(_Condition.wait)
203432054/203432055 1564.325    0.000 1564.325    0.000 __builtin__:0(<method 'acquire' of 'thread.lock' objects>)
13893115/13893158  623.255    0.000 10083.479    0.001 Queue.py:150(PriorityQueue.get)
178002954  485.361    0.000  485.361    0.000 time:0(time)
101874671  463.914    0.000  463.914    0.000 __builtin__:0(min)
 24576283  446.015    0.000  731.661    0.000 threading.py:147(_RLock.acquire)
 20650850  429.269    0.000 1753.586    0.000 GangaThread.py:10(GangaThread.decorated)
35396110/54437560  394.032    0.000  916.908    0.000 lexer.py:616(Python3TracebackLexer.get_tokens_unprocessed)
 24576282  357.426    0.000  523.322    0.000 threading.py:187(_RLock.release)
366362488  283.677    0.000  283.677    0.000 __builtin__:0(<method 'match' of '_sre.SRE_Pattern' objects>)
 67826741  202.180    0.000  202.180    0.000 threading.py:64(_RLock._note)
  4249734  186.170    0.000 1303.766    0.000 html.py:738(HtmlFormatter._format_lines)
```

and now who is calling the first ones in the table above

```
pstats% callers
   Ordered by: internal time

Function                                                                          was called by...
                                                                                      ncalls  tottime  cumtime
time:0(sleep)                                                                     <- 2109382/2109379  115.992  115.992  Registry.py:254(RegistryFlusher.run)
                                                                                   932748/932747   50.326   50.326  SessionLock.py:114(SessionLockRefresher.run)
                                                                                   6755424/6755423  344.783  344.784  TaskRegistry.py:57(TaskRegistry._thread_main)
                                                                                   13709/13708    0.757    0.757  stacktracer.py:90(TraceDumper.run)
                                                                                   101861067/101861039 4790.758 4790.760  threading.py:309(_Condition.wait)
                                                                                        52/0    0.002    0.002  time:0(sleep)
threading.py:309(_Condition.wait)                                                 <- 1356775/1356774  297.449  862.149  Local_GangaMC_Service.py:571(JobRegistry_Monitor.run)
                                                                                   13893158/13893142 2832.294 8983.367  Queue.py:150(PriorityQueue.get)
                                                                                   705964/705959  325.688 1121.431  Queue.py:150(Queue.get)
                                                                                         3/0    0.000    0.001  threading.py:309(_Condition.wait)
                                                                                     107/106    0.003    0.019  threading.py:600(_Event.wait)
                                                                                         2/0    0.000    0.000  time:0(sleep)
__builtin__:0(<method 'acquire' of 'thread.lock' objects>)                        <-    2262    0.004    0.004  Queue.py:86(Queue.qsize)
                                                                                        2262    0.003    0.003  Queue.py:107(Queue.put)
                                                                                    13893158  115.596  115.596  Queue.py:150(PriorityQueue.get)
                                                                                      705963    4.861    4.861  Queue.py:150(Queue.get)
                                                                                    24495405  147.286  147.286  threading.py:147(_RLock.acquire)
                                                                                     1356777    6.821    6.821  threading.py:220(_RLock._acquire_restore)
                                                                                    14599213  119.928  119.928  threading.py:297(_Condition._acquire_restore)
                                                                                    14603840  112.348  112.348  threading.py:300(_Condition._is_owned)
                                                                                   133773055/133773054 1057.476 1057.476  threading.py:309(_Condition.wait)
                                                                                          81    0.001    0.001  threading.py:860(Thread.__stop)
                                                                                          39    0.000    0.000  time:0(sleep)
Queue.py:150(PriorityQueue.get)                                                   <-    27/0    0.000    0.006  Queue.py:150(PriorityQueue.get)
                                                                                   13893125/13893115  623.255 10083.479  WorkerThreadPool.py:61(WorkerThreadPool.__worker_thread)
                                                                                         6/0    0.000    0.001  threading.py:309(_Condition.wait)
```

So I see that the monitoring thread in the tasks `TaskRegistry.py:57(TaskRegistry._thread_main)` is one of the sinners but that the main problem is coming from `Queue.py:150(PriorityQueue.get)` 

It turns out that this is a known issue, see http://blog.codedstructure.net/2011/02/concurrent-queueget-with-timeouts-eats.html. Ganga indeed has a huge number of these `queue.get` calls with a timeout (it is how we figure out if the threads should stop or not. This is all related to CPU activity when Ganga is idle. Seems a good place to start though.

**Comment by mesmith75** [comment] 2019-08-06 17:05
I wonder if that is still an issue with newer python versions? The comments seem to suggest it may be improved.

**Comment by egede** [comment] 2019-08-07 04:18
Running the same profiling in the `python3` branch gives less information. I am not sure why. However, the idle `ganga` session is still using high CPU, even when there is nothing to monitor. Running `strace -f` on the process reveals a huge number of calls of the type
```
[pid 30903] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=136, tv_nsec=346691436}) = 0
```
which to me looks like almost the same problem. I thought about as a test to make all the threads blocking. This should still leave Ganga working but it will be unable to shut down cleanly. Ok for testing.

**Comment by JacekHoleczek** [comment] 2019-08-07 07:55
Now, when the "high CPU usage" problem is confirmed, I would like to return to another problems that I reported here.

I think I can live with the misbehaving logger. Under normal conditions, the amount of "screen output" is not that big (just the usual messages about jobs being submitted and completed) so, I think I can enforce `_interactive_cache = False` (note: `--very-quiet` is not an option, I really want to see what happens).

However, I would really like to get the misbehaving ganga prompt fixed (pressing any key destroys the last printed "INFO" line, or maybe even two lines). It seems to me that the origin of this problem is that the prompt uses two lines. I haven't found any option in the ".gangarc" file to (re)define my own prompt (e.g. I could imagine having a one line "[HH:MM:SS] In [...]:" prompt).

**Comment by egede** [comment] 2020-03-05 08:39
CPU issue was solved, so closing.

**Closed as completed by egede** 2020-03-05 08:39 UTC
