### ISSUE TITLE
problem with ARC backend

### ISSUE THREAD

**Issue by afortiorama** [ganga-devs/ganga#1151] opened 2017-11-01 13:46 UTC
I submit a job

```
j = Job()
j.application = Executable(exe=File('/bin/bash'), args=['job.sh'])
j.backend=ARC()
j.backend.CE='ce02.tier2.hep.manchester.ac.uk'
j.inputfiles = [LocalFile('job.sh')]
j.submit()
```

the job gets correctly submitted but cannot be sync'd

```
Registry Slice: jobs (1 objects)
--------------
    fqid |    status |      name | subjobs |    application |        backend |                             backend.actualCE |                       comment
-------------------------------------------------------------------------------------------------------------------------------------------------------------
    2648 | submitted |           |         |     Executable |            ARC |              ce02.tier2.hep.manchester.ac.uk |                              

WARNING  jobs not found in XML file: arcsync will be executed to update the job information
WARNING  jobs not found in XML file: arcsync will be executed to update the job information
#### 10th of lines like this later #######
WARNING  Command interrupted - timeout 300s reached: arcsync  -j ~/.arc/gangajobs.xml -f -c hce02.tier2.hep.manchester.ac.uk
WARNING  exit status [-15] of command arcsync  -j ~/.arc/gangajobs.xml -f -c hce02.tier2.hep.manchester.ac.uk
ERROR    Unable to sync ARC jobs. Error:
```

there is a spurious 'h' in front of the CE FQDN. 

After running the arcsync command manually with the right hostname things are still not well.  I get the needed sync and finally get some output back but the job failed with this error message

```
aforti@vm7>gunzip /home/aforti/gangadir/workspace/aforti/LocalXML/2648/output/stderr.gz
aforti@vm7>cat /home/aforti/gangadir/workspace/aforti/LocalXML/2648/output/stderr
./bash: job.sh: Too many levels of symbolic links

```
jobs.sh is a simple bash script and when I submit with arcsub it works well.

This happens with all ganga versions I tested in cvmfs.

**Comment by afortiorama** [comment] 2017-11-01 14:47
The bash script error was a red herring forget about that. But the arcsync problem  is still there.

**Comment by mesmith75** [comment] 2017-11-01 15:05
Thanks, looks like a bug here: https://github.com/ganga-devs/ganga/blob/develop/python/Ganga/Lib/LCG/Grid.py#L1033 .
We can get rid of that `h`

**Comment by egede** [comment] 2017-11-01 16:09
The use of "blame" shows that a fat finger put in an extra "(" when the new credential system was added. I guess the problem is that we do not have any ARC tests.

**Comment by afortiorama** [comment] 2017-11-01 19:02
Hi,

when is the next release?

cheers
alessandra

**Comment by mesmith75** [comment] 2017-11-02 11:18
Hopefully that fix will get merged today and so be in the DEV version on CVMFS tomorrow. A release should follow in the next week - there are a few other things that need sorting.

**Closed** 2017-11-03 09:49 UTC
