### ISSUE TITLE
1 background thread(s) still running: ['SessionLockRefresher'].

### ISSUE THREAD

**Issue by JacekHoleczek** [ganga-devs/ganga#504] opened 2016-05-21 07:25 UTC
On a remote "user interface" machine which runs "SL 6" with python 2.6.6 ...
... with Ganga 6.0.44, I occasionally have this problem (usually when I try to exit "ganga" after running it for a long time, when my task is "completed") but I think I (almost?) never need to "force the exit" (though it might take up to something like 10 minutes, clicking "n" every couple of seconds, before it exits nicely).
... with Ganga 6.1.20, this problem happens every second time I run it and it seems that I always need to "force the exit" (even if I just start "ganga" and then immediately try to exit it without any other actions):
```
[...]$ ganga 
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7
WARNING  Ganga will soon be depending on Python 2.7. You have Python 2.6 installed. See https://github.com/ganga-devs/ganga/wiki/Python-2.7

*** Welcome to Ganga ***
Version: 6.1.20
Documentation and support: http://cern.ch/ganga
Type help() or help('index') for online help.

This is free software (GPL), and you are welcome to redistribute it
under certain conditions; type license() for details.


INFO     reading config file /.../.gangarc

[02:04:14]
Ganga In [1]: exit()

Job status update or output download still in progress (shutdown not completed after 6 seconds).
1 background thread(s) still running: ['SessionLockRefresher'].
Do you want to force the exit (y/[n])? y
INFO     Stopping Job processing before shutting down Repositories
WARNING  Shutdown forced. 1 background thread(s) still running: ['SessionLockRefresher']
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
```
Well, assuming that my task is still "running" and I "force the exit" (that means I exit my running "ganga" for some reason while my task is still NOT "completed"). Can I safely re-run "ganga" again in order to "proceed" with my task? Do I need to execute any additional commands when I re-start "ganga" in such cases?

**Comment by rob-c** [comment] 2016-05-22 20:06
@JacekHoleczek  I believe the shutdown mechanism is being looked into by @drmarkwslater ahead of a 6.1.21 release of Ganga.
I don't know if any changes are planned with the shutting down of this thread but it may be worth looking into.

The short answer to your questions is that this background process is relatively harmless to force exit from Ganga and it should be safe to just start again.
At worst cause some stale lockfiles to be left around which Ganga will happily cleanup after they've timed out, you can manually delete these if they're locking a job/task you know you should have access to.
_(I've been planning to look at the configuration options here as to how often we refresh lockfiles and when to regard them as stale and such but this has been quite low priority)_

I would be interested to know what sort of filesystem you're running on and if you could provide a copy of  ```~/gangadir/thread_trace.html``` whilst Ganga is stuck trying to complete this particular background task during shutdown. (i.e. if it's been trying to shutdown for 2 min or more can you make a copy of this file it could be very helpful). This is one of the few outstanding threads I'm still seeing having trouble myself but I'm really struggling to re-create the problems associated with it during shutdown.

**Comment by JacekHoleczek** [comment] 2016-05-22 21:55
I started Ganga 6.1.20 and executed "exit()" ... and after about 11 minutes (so after pressing something like 50 times "n"):
<!doctype html>
<html lang="en">
<head>
<meta charset=utf-8>
<title>Current Ganga Threads</title>
</head><body><h1>Current Ganga Threads</h1>
<h2>GANGA_Update_Thread_shutdown</h2>
<pre>  File "/usr/lib64/python2.6/threading.py", line 504, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/...MyGangaDistribution.../install/6.1.20/python/Ganga/Core/GangaThread/GangaThreadPool.py", line 191, in __do_shutdown__
    t.stop()
  File "/...MyPrivateGangaDistribution.../install/6.1.20/python/Ganga/Core/MonitoringComponent/Local_GangaMC_Service.py", line 833, in stop
    self.__cleanUpEvent.wait()
  File "/usr/lib64/python2.6/threading.py", line 395, in wait
    self.__cond.wait(timeout)
  File "/usr/lib64/python2.6/threading.py", line 239, in wait
    waiter.acquire()
</pre>
<h2>GANGA_Update_Thread_SessionLockRefresher</h2>
<pre>  File "/usr/lib64/python2.6/threading.py", line 504, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/...MyPrivateGangaDistribution.../install/6.1.20/python/Ganga/Core/GangaRepository/SessionLock.py", line 162, in run
    time.sleep(0.05 + random.random() * 0.05)
</pre>
<h2>Dummy-8</h2>
<pre>  File "/...MyPrivateGangaDistribution.../install/6.1.20/python/Ganga/Core/InternalServices/ShutdownManager.py", line 135, in _ganga_run_exitfuncs
    func(*targs, **kargs)
  File "/...MyPrivateGangaDistribution.../install/6.1.20/python/Ganga/Core/GangaThread/GangaThreadPool.py", line 74, in shutdown
    self._really_shutdown(should_wait_cb)
  File "/...MyPrivateGangaDistribution.../install/6.1.20/python/Ganga/Core/GangaThread/GangaThreadPool.py", line 118, in _really_shutdown
    if not should_wait_cb(total_time, critical_thread_ids, non_critical_thread_ids):
  File "/...MyPrivateGangaDistribution.../install/6.1.20/python/Ganga/Core/__init__.py", line 106, in should_wait_interactive_cb
    resp = raw_input(msg)
</pre>
<h2>Thread-1</h2>
<pre>  File "/usr/lib64/python2.6/threading.py", line 504, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/...MyPrivateGangaDistribution.../install/6.1.20/python/Ganga/Core/GangaRepository/Registry.py", line 342, in trackandRelease
    time.sleep(0.5)
</pre>
<h2>Thread-2</h2>
<pre>  File "/usr/lib64/python2.6/threading.py", line 504, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/...MyPrivateGangaDistribution.../install/6.1.20/python/Ganga/Utility/stacktracer.py", line 94, in run
    self.stacktraces()
  File "/...MyPrivateGangaDistribution.../install/6.1.20/python/Ganga/Utility/stacktracer.py", line 107, in stacktraces
    fout.write(stacktraces())
  File "/...MyPrivateGangaDistribution.../install/6.1.20/python/Ganga/Utility/stacktracer.py", line 55, in stacktraces
    trace = traceback.format_stack(stack)
</pre>
<small>2016-05-22T21:43:06.296663</small>
</body>
</html>

**Comment by rob-c** [comment] 2016-05-23 08:27
Hi again, thanks for the trace of Ganga stalling. I'm aware that we're touching the same code in the Registry as seems to be cropping up here in 6.1.21. This may be enough to cure the problems that you're seeing. My suspicion is that the ```SeessionLockRefresher``` isn't receiving a shutdown command due to a ```Registry``` bug.

I'll try and leave a Ganga session open for 15min before closing it on the latest code and see if this still persists, would this be long enough to reproduce the problem?

**Comment by JacekHoleczek** [comment] 2016-05-23 08:39
Just to make it clear.
I start the new "ganga" and as soon as I see the "Ganga In [1]:" prompt I type "exit()".
Do you want me to wait 15 minutes before issuing "exit()"?

BTW. Has anybody seen my recent : https://github.com/ganga-devs/ganga/pull/38#issuecomment-220762263

**Comment by rob-c** [comment] 2016-05-23 08:44
@JacekHoleczek my understanding was that this is only really seen for sessions which have been open for a while before exiting?
I can setup a bash shell script to open/close ganga many times O(100) to see if I get it to stall again. 

Unfortunately I'm not fully up to speed on the Python 2.7 requirement from Ganga atm, I think you'll have to wait to see if another developer who knows a bit more than myself can reply on #38.

**Comment by JacekHoleczek** [comment] 2016-05-23 08:55
In my first entry above, I write that with Ganga 6.0.44 I have this problem from time to time when the session is opened for a long time (though I don't remember I needed to "force the exit").
I have just started to work with Ganga 6.1.20 and currently I am not able to run my tasks (due to some "incomplatibilities" with the old Ganga?).
So, for the time being, Ganga 6.1.20 is always running for small amounts of time (i.e. for some very short tests).
As I write in my entry above, Ganga 6.1.20 gets stuck even if I do nothing (i..e. immediately after I start it, I try to "exit()" it) and I don't really remember that something like this happened to me with Ganga 6.0.44.

**Comment by rob-c** [comment] 2016-05-23 09:06
@JacekHoleczek When you say that this gets stuck, what size repository for the jobs and tasks are being loaded by Ganga 6.1.20?

Ganga 6.1.x will make some effort to fix job indexes which were often very broken in 6.0.44 and prior which can explain that on the first startup it will be very slow for a few minutes as a lot of data is read in from disk. I'm trying to make sure that an appropriate warning is displayed to the user that this is happening in 6.1.21.
Once this has finished and cleanly exited Ganga will be in a better working state that should work in the future.

What incompatibilities are you exactly seeing in 6.1.20 with regard to Tasks from 6.0.44?
I was under the impression that most of the known incompatibilities had been fixes so if there is a bug here then I suspect it needs to be addressed.

All of this being said, @drmarkwslater could this be to do with lazy loading and Tasks not fully working together?

**Comment by JacekHoleczek** [comment] 2016-05-23 09:56
For these tests, I do not load anything (i.e. "RUNTIME_PATH" is empty).
I only set "EDG_ENABLE = False" and "GLITE_ENABLE = False".

BTW. I just tried it on an Ubuntu 14.04.4 LTS / x86_64 machine running Python 2.7.6 ... and I also get this problem with Ganga 6.1.20.
I start "ganga" and, as soon as I see the "Ganga In [1]:" prompt, I type "exit()" and then it sometimes gets stuck .. here's the "thread_trace.html" after I pressed "n" for something like 60 times, so waiting about 11 minutes:
<!doctype html>
<html lang="en">
<head>
<meta charset=utf-8>
<title>Current Ganga Threads</title>
</head><body><h1>Current Ganga Threads</h1>
<h2>GANGA_Update_Thread_shutdown</h2>
<div class="highlight" style="background: #f8f8f8"><pre style="line-height: 125%"><span></span>  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">783</span>, in __bootstrap
    <span style="color: #008000">self</span><span style="color: #666666">.</span>__bootstrap_inner()
  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">810</span>, in __bootstrap_inner
    <span style="color: #008000">self</span><span style="color: #666666">.</span>run()
  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">763</span>, in run
    <span style="color: #008000">self</span><span style="color: #666666">.</span>__target(<span style="color: #666666">*</span><span style="color: #008000">self</span><span style="color: #666666">.</span>__args, <span style="color: #666666">**</span><span style="color: #008000">self</span><span style="color: #666666">.</span>__kwargs)
  File <span style="color: #008000">&quot;/opt/GANGA/6.1.20/install/6.1.20/python/Ganga/Core/GangaThread/GangaThreadPool.py&quot;</span>, line <span style="color: #666666">191</span>, in __do_shutdown__
    t<span style="color: #666666">.</span>stop()
  File <span style="color: #008000">&quot;/opt/GANGA/6.1.20/install/6.1.20/python/Ganga/Core/MonitoringComponent/Local_GangaMC_Service.py&quot;</span>, line <span style="color: #666666">833</span>, in stop
    <span style="color: #008000">self</span><span style="color: #666666">.</span>__cleanUpEvent<span style="color: #666666">.</span>wait()
  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">620</span>, in wait
    <span style="color: #008000">self</span><span style="color: #666666">.</span>__cond<span style="color: #666666">.</span>wait(timeout)
  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">339</span>, in wait
    waiter<span style="color: #666666">.</span>acquire()
</pre></div>

<h2>GANGA_Update_Thread_SessionLockRefresher</h2>
<div class="highlight" style="background: #f8f8f8"><pre style="line-height: 125%"><span></span>  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">783</span>, in __bootstrap
    <span style="color: #008000">self</span><span style="color: #666666">.</span>__bootstrap_inner()
  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">810</span>, in __bootstrap_inner
    <span style="color: #008000">self</span><span style="color: #666666">.</span>run()
  File <span style="color: #008000">&quot;/opt/GANGA/6.1.20/install/6.1.20/python/Ganga/Core/GangaRepository/SessionLock.py&quot;</span>, line <span style="color: #666666">162</span>, in run
    time<span style="color: #666666">.</span>sleep(<span style="color: #666666">0.05</span> <span style="color: #666666">+</span> random<span style="color: #666666">.</span>random() <span style="color: #666666">*</span> <span style="color: #666666">0.05</span>)
</pre></div>

<h2>Thread-1</h2>
<div class="highlight" style="background: #f8f8f8"><pre style="line-height: 125%"><span></span>  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">783</span>, in __bootstrap
    <span style="color: #008000">self</span><span style="color: #666666">.</span>__bootstrap_inner()
  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">810</span>, in __bootstrap_inner
    <span style="color: #008000">self</span><span style="color: #666666">.</span>run()
  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">763</span>, in run
    <span style="color: #008000">self</span><span style="color: #666666">.</span>__target(<span style="color: #666666">*</span><span style="color: #008000">self</span><span style="color: #666666">.</span>__args, <span style="color: #666666">**</span><span style="color: #008000">self</span><span style="color: #666666">.</span>__kwargs)
  File <span style="color: #008000">&quot;/opt/GANGA/6.1.20/install/6.1.20/python/Ganga/Core/GangaRepository/Registry.py&quot;</span>, line <span style="color: #666666">342</span>, in trackandRelease
    time<span style="color: #666666">.</span>sleep(<span style="color: #666666">0.5</span>)
</pre></div>

<h2>Thread-2</h2>
<div class="highlight" style="background: #f8f8f8"><pre style="line-height: 125%"><span></span>  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">783</span>, in __bootstrap
    <span style="color: #008000">self</span><span style="color: #666666">.</span>__bootstrap_inner()
  File <span style="color: #008000">&quot;/usr/lib/python2.7/threading.py&quot;</span>, line <span style="color: #666666">810</span>, in __bootstrap_inner
    <span style="color: #008000">self</span><span style="color: #666666">.</span>run()
  File <span style="color: #008000">&quot;/opt/GANGA/6.1.20/install/6.1.20/python/Ganga/Utility/stacktracer.py&quot;</span>, line <span style="color: #666666">94</span>, in run
    <span style="color: #008000">self</span><span style="color: #666666">.</span>stacktraces()
  File <span style="color: #008000">&quot;/opt/GANGA/6.1.20/install/6.1.20/python/Ganga/Utility/stacktracer.py&quot;</span>, line <span style="color: #666666">107</span>, in stacktraces
    fout<span style="color: #666666">.</span>write(stacktraces())
  File <span style="color: #008000">&quot;/opt/GANGA/6.1.20/install/6.1.20/python/Ganga/Utility/stacktracer.py&quot;</span>, line <span style="color: #666666">55</span>, in stacktraces
    trace <span style="color: #666666">=</span> traceback<span style="color: #666666">.</span>format_stack(stack)
</pre></div>

<h2>Dummy-8</h2>
<div class="highlight" style="background: #f8f8f8"><pre style="line-height: 125%"><span></span>  File <span style="color: #008000">&quot;/opt/GANGA/6.1.20/install/6.1.20/python/Ganga/Core/InternalServices/ShutdownManager.py&quot;</span>, line <span style="color: #666666">135</span>, in _ganga_run_exitfuncs
    func(<span style="color: #666666">*</span>targs, <span style="color: #666666">**</span>kargs)
  File <span style="color: #008000">&quot;/opt/GANGA/6.1.20/install/6.1.20/python/Ganga/Core/GangaThread/GangaThreadPool.py&quot;</span>, line <span style="color: #666666">74</span>, in shutdown
    <span style="color: #008000">self</span><span style="color: #666666">.</span>_really_shutdown(should_wait_cb)
  File <span style="color: #008000">&quot;/opt/GANGA/6.1.20/install/6.1.20/python/Ganga/Core/GangaThread/GangaThreadPool.py&quot;</span>, line <span style="color: #666666">118</span>, in _really_shutdown
    <span style="color: #008000; font-weight: bold">if</span> <span style="color: #AA22FF; font-weight: bold">not</span> should_wait_cb(total_time, critical_thread_ids, non_critical_thread_ids):
  File <span style="color: #008000">&quot;/opt/GANGA/6.1.20/install/6.1.20/python/Ganga/Core/__init__.py&quot;</span>, line <span style="color: #666666">106</span>, in should_wait_interactive_cb
    resp <span style="color: #666666">=</span> raw_input(msg)
</pre></div>

<small>2016-05-23T09:54:20.669570</small>
</body>
</html>

**Comment by rob-c** [comment] 2016-05-23 10:06
@JacekHoleczek What size repositories are you working with? It's likely that something could be loading a lof of jobs from disk which explains the very sow shutdown and I'd like to rule this out.

Have you tried either running with ```--no-mon``` or executing a python script which contains only ```exit()``` as these will run without the monitoring so I'm interested to know if this shuts down faster.

Alternatively you could try to startup/shutdown with ```[Tasks] disableTaskMon=True``` in your .gangarc so that I can see the effect of starting up without the tasks monitoring loop running.

**Comment by drmarkwslater** [comment] 2016-05-23 10:33
This is something I'm looking into with #459. This at least shows that it happens in Core as well as GangaAtlas. I'll let you know if I can narrow things down any more...

**Comment by JacekHoleczek** [comment] 2016-05-23 10:49
Note that in both cases, on "SL6" and "Ubuntu 14.04.4 LTS", I ALWAYS start with a completely "fresh" Ganga 6.1.20 setup. That means I recreate ".gangarc" and "gangadir" from scratch (i.e. there are NO remnants from any previous jobs, tasks, ...).

**Comment by rob-c** [comment] 2016-05-23 10:51
Hmm. I'll have a play on my openSuSE machine and see if I can replicate this (strange I don't see this on lxplus but that is running on AFS which is a special case.)
I'll run a bash script to restart Ganga a lot on my laptop and see if anything obvious crops up. I'm putting in some light code changes in #507 which may or may not help debugging this.

**Comment by rob-c** [comment] 2016-06-21 11:18
@JacekHoleczek Is there any chance you can try the latest develop code I think this has been identified as bug in handling of file locks and since fixed.

**Comment by JacekHoleczek** [comment] 2016-06-21 15:24
So, I downloaded new ganga using "git clone https://github.com/ganga-devs/ganga.git".
On "Ubuntu 14.04.4 LTS" it seems to work (I tried to start it and then execute "exit()" many times without problems).
On "SLC6", I am not able to run this new ganga. I get:
```
(...)
Would you like to create default config file ~/.gangarc with standard settings ([y]/n) ?

INFO     Creating ganga config file /.../.gangarc
Press <Enter> to continue.

Unknown IPython version: 0.13.2
INFO     Stopping the monitoring component...
INFO     Stopping Job processing before shutting down Repositories
INFO     Shutting Down Ganga Repositories
INFO     Registry Shutdown
[...]$ 
```

**Comment by rob-c** [comment] 2016-06-21 15:38
@JacekHoleczek you ideally need to install via `pip install --user` or setup a more upto date version of IPython on the system you're using.
We dropped support for everything pre IPython 1.0 a while ago I think unfortunately as we needed to make a jump to support something better than the standard which used to be very old.

**Comment by rob-c** [comment] 2016-06-21 15:39
It sounds like the original issue has probably gone away in this case. I'll close this issue tomorrow if everything looks OK 👍

**Comment by JacekHoleczek** [comment] 2016-06-21 17:28
Using the trick with replacing "6.1.20" with "git clone", I was able to try it on "SLC6" now, and it seems to work (I tried to start it and then execute "exit()" many times without problems).

**Closed** 2016-06-21 21:37 UTC
Labels: bug, Core
