### ISSUE TITLE
Job equality broken

### ISSUE THREAD

**Issue by milliams** [ganga-devs/ganga#229] opened 2016-02-26 09:43 UTC
There is a test in the legacy suite (*JobCopyConstructor.gpi*) which looks like:
```python
j = Job()
j2 = j.copy()
j3 = Job(j)

assert j == j2
assert j2 == j3
```
Naïvely I expected this to fail as things like the `id` would have changed but I checked the `Job`'s schema and it has `comparable=0` set on the `id`  (and some other items). 

Looking back at previous results I see that this test was failing in 6.0.44, passing in 6.1.14, still passing in 6.1.13 and failing again in 6.1.14.

The code as written should have this test passing as `GangaObject` equivalence ignores attributes with `comparable=0`. The failure for 6.1.16 is due to `postprocessors` not equating which is a bug which needs looking into.

The larger question is *what do we want object equality to look like?* In my opinion two `GangaObject`s should only be equal if *all* their schema attributes are the same. `__eq__` at the moment seems to be performing an "are these two objects a bit similar" test. If we really want this latter comparison then an `is_similar_to()` function might make sense.

Thoughts?

**Comment by rob-c** [comment] 2016-02-26 10:14
This one has bugged me a lot in the past.
I think we need to take a look at what in the schema as to what are comparable attributes, I've no idea if the post-processor was designed to correctly pass an equality test or not.
There is already a fix for this in the Schema attribute isn't there some are never expected to be the same aka ```j.id``` so I would just opt to make the post-processor non comparable unless we know we can fix the equality function for these classes. (I think this means we need to check the default in the Schema for this attribute in this case)

**Comment by egede** [comment] 2016-02-26 12:57
j.postprocessor just contains a default MultiProcessor object in the test above. Not obvious to me why the postprocessors are not declared equal. I feel it is slightly dangerous just to declare the postprocessors non-comparable when we do not understand what the problem is.

**Comment by rob-c** [comment] 2016-02-26 12:59
This sounds like a bug in the postprocessor then which should be checked within this class, unless we suspect that the comparison of the schema is somehow broken in a deeper way. (Seems to work fine for most things)

**Comment by milliams** [comment] 2016-02-26 13:00
@egede I agree. I'd much rather make the code work in the way it should and then at a later time, perhaps reconsider the equality definition we want. I'll look into the `MultiProcessor` equality for the next release if possible (and port the appropriate test).

**Comment by alexanderrichards** [comment] 2016-02-26 13:28
> In my opinion two GangaObjects should only be equal if all their schema attributes are the same

:+1:

I totally agree with this. This is I think the _expected_ behaviour of a comparison between GangaObjects.

There is room for discussion however about what **all schema attributes** means then. i.e.  do we want to ignore `id` and have objects with similar non `comparable` attributes compare equal. Or do we want it to essentially refer to **all** schema attributes such that the above fails as matt says.

The third option of course is to only have them equal if they are indeed the same object in memory which would in a practical sense look the same as the latter from above as the id would be expected to be different (however it could be forced to be the same).

 I flip flop between which I consider the most _expected_ behaviour from the users point of view. I suspect also there may be a dependence on the particular GangaObject in question as to what the _expected_ behaviour would be. With Jobs for example I think that people would not expect two Jobs with identical parameters (except the id) to compare equal as there is a sense that they are distinct jobs. However my feeling is that for a GangaList, the reverse is probably true.

> If we really want this latter comparison then an is_similar_to() function might make sense.

I don't think we want this.

**Comment by egede** [comment] 2016-02-26 13:46
@alexanderrichards In terms of the expected behaviour, I actually think that we should indeed make all the properties (even the id agree). In that way, I would expect

```
j =Job()
j2 = j
j==j2 # True
j = Job(j) # False
j = j,copy() # False
```
This is about the future and does not explain if there is something odd going on at the moment. We also need to ensure that `j.copy()` and `Job(j)` result in the same behaviour.

**Comment by rob-c** [comment] 2016-02-26 13:52
The ```Job(j)``` and ```j.copy()``` is related to the handling of the arguments in the Proxy, and in a future commit (getting rid of the ```__constructor__``` in 6.1.18) the Proxy makes use of the ```copyFrom``` method when taking a single argument of the same type as the proxied class being generated.

**Comment by alexanderrichards** [comment] 2016-02-26 13:53
This is indeed about the future but It's important we should make sure that we are all clear what the expected behaviour should be otherwise we will repeat the same mistakes again and again.


> I actually think that we should indeed make all the properties (even the id agree)

I agree with this. But does this then render the `comparable` flag obsolete?

**Comment by rob-c** [comment] 2016-02-26 13:54
We can't render this flag obsolete without taking things like ```id``` out of the schema which doesn't exist in all objects.
We can remove it but then we need equality operators everywhere or to have numerous exceptions in the base class.

**Comment by milliams** [comment] 2016-02-26 13:55
@alexanderrichards Indeed it would render the `comparable` flag obsolete. This *feels* like the right thing to do but we need to be careful we're not breaking some assumption of we change this current behaviour.

**Comment by rob-c** [comment] 2016-02-26 13:56
Having the ```id``` agree means that we're handling the ```copy``` vs the ```deepcopy``` functions correctly which we aren't atm.
It would be nice to have the ```copy``` do what we expect and just return a reference but when we want to compare ```j1 == deepcopy(j1)``` we run into problems.

**Comment by alexanderrichards** [comment] 2016-02-26 13:56
I agree this _feels_ right to me as well

**Comment by rob-c** [comment] 2016-02-26 14:00
In the top example do we expect:
```
j1 = Job()
j2 = j1.copy()
assert j1 is j2
```
to be correct or do we still expect the copy method to perform a deep copy on job objects?

**Comment by alexanderrichards** [comment] 2016-02-26 14:09
since `j1` and `j2` in this example would have different `id` values we would expect this to fail however be careful about the _exact_ comparison that's going on `==` is not the same as `is`. The latter is the object comparison which would state that they are not the same object whilst the former would call the `__eq__` method to work out their value equivalence in this case not the same as their `id` attribute would be different

**Comment by milliams** [comment] 2016-02-26 14:17
@drmarkwslater and I have been discussing the last few days and we agreed that in the GPI layer, `proxy_obj.copy()` should effectively do a `deepcopy` (with a few exceptions such as a `Job`'s `id` being increased).

In pure-Python land, `copy.copy()` should do a shallow copy and `copy.deepcopy()` should do a recursive deepcopy.

**Comment by rob-c** [comment] 2016-02-26 14:18
The equality operator handles non comparable schema attributes to make the equality check work when we perform a deepcopy so people can test if their job is configured in the same way.
Unless we're looking to modify the schema or handling of the schema in a big way surely this is handled by knowing if the attribute is non comparable?

This touches on the issue that 2 prepared Executbles aren't the same even though they may be configured in the same way.

I would expect the above to fail because yes we expect a deepcopy here.

As for the original bug I suspect that there is a bug in the schema or design or the postprocessors.

**Comment by drmarkwslater** [comment] 2016-02-26 14:19
I'm also of the opinion that `==` should mean that all schema attributes also satisfy `==`, thus rendering comparable obsolete (or essentially not allow comparable set to 0 in a GangaObject). However, there is something to be said about differences between proxy and non-proxy objects, i.e. are you doing this in the GPI or not which may have an impact.

And in fact @milliams just said what I was going to write here :smile:

**Comment by rob-c** [comment] 2016-02-26 14:21
Should we be having a different ```__eq__``` behaviour in the proxy layer in this case.

The one in GangaObject should perform an exact equality check but the one in the Proxy layer knows to ignore certain objects in the comparison.

aka if we have a hidden internal attribute in 2 jobs which are the same to the user the user should expect that they both satisfy ```==```

**Comment by alexanderrichards** [comment] 2016-02-26 14:24
umm... I'm not sure that's what we are saying. I think your asking for trouble if you have `__eq__` doing different things in the Proxy layer (I may be wrong but it feels like it could be a disaster).

I think that what we are saying is that `__eq__` will always compare **all** schema attributes `==`. but that the `copy` method will produce a deepcopy in the proxy layer vs a shallow copy in the python layer

**Comment by drmarkwslater** [comment] 2016-02-26 14:24
This is true - it clouds the issue a little with Jobs as users obviously think jobs are different, but for an application that has a hidden attribute, it would be confusing for a user to compare 2 that as far as they are concerned are the same but are coming back as not equal. Tricky...

**Comment by alexanderrichards** [comment] 2016-02-26 14:29
hmm.. I see your point. What is done currently for `hidden` attributes? are they automatically `comparable=0` This is exactly why we should discuss what we want the behaviour to be **before** we go away and attempt to fix something.

**Comment by rob-c** [comment] 2016-02-26 14:29
The ```__eq__``` in the Proxy layer would allow for us to check for proxied vs non proxied checks which are bad:
aka:
for: ```myJob=Job(); myJob2=Job()``` (working in IPython land)

```myJob == stripProxy(myJob2)``` should throw an exception imo.
```stripProxy(myJob) == stripProxy(myJob2)``` should return false
```myJob == myJob2``` should return True if they're configured in the same way

**Comment by milliams** [comment] 2016-02-26 14:29
For clarity, there are three different ways to copy in Ganga:

1. `import copy; copy.copy(obj)` this copies the object but keeps all references intact below that. It is overridden by implementing `__copy__` in your class.
2. `import copy; copy.deepcopy(obj)` this clones every layer recursively.  It is overridden by implementing `__deepcopy__` in your class
3. `j = Job(); j.copy()` this is a Ganga-specific thing which exists only in the proxy layer which calls `GangaObject.clone()`. Really it neither copies, nor clones but rather "makes another object which is similar but with some differences" such as unpreparing etc. All three are doing very different things at various points.

**Comment by egede** [comment] 2016-02-26 14:30
@drmarkwslater I think we need to get an overview of what we actually use hidden attributes for.

**Comment by rob-c** [comment] 2016-02-26 14:31
This whole use of hidden attributes has come up before a few times and I think it would be a good thing to discuss in a meeting.

**Comment by alexanderrichards** [comment] 2016-02-26 14:32
agreed, This issue is getting long and involved, we should clearly discuss it at next weeks meeting

**Comment by drmarkwslater** [comment] 2016-02-26 14:34
Actually - do we fancy another face to face meet up? We've now got several major issues for discussion backed up and so it might be worth it...

**Comment by rob-c** [comment] 2016-02-26 14:35
@drmarkwslater That was what I had in mind tbh

**Comment by alexanderrichards** [comment] 2016-02-26 14:37
great idea, where ever it's decided to hold it, can we make sure there is a vidyo connection as I don't know if I will be funded to go :disappointed:

**Comment by drmarkwslater** [comment] 2016-02-26 14:58
Then that's a good argument to have a meeting at Imperial then :smile:

**Comment by milliams** [comment] 2016-03-17 13:30
Back to the topic of this bug, it was being caused by the way that Python determines truthiness. `MultiPostProcessor` was exposing a sequence interface which means that `__len__` was the number of items in its internal list. When this list was empty, the object evaluated as `False` and so this bit of login in `GangaObject.__eq__`:
```python
if not node:
    return 0
```
was meaning that an empty `MultiPostProcessor` was never equal to anything. The solution is to remove that check as I believe it's faulty. I'll put in a PR for it.

We still need the discussion about the other things in this issue but that's for another day.

**Closed** 2016-03-22 18:14 UTC
Labels: bug, Core, in progress, question
