### ISSUE TITLE
Copy Constructor on Job doesn't create fqid properly

### ISSUE THREAD

**Issue by drmarkwslater** [ganga-devs/ganga#74] opened 2016-01-04 14:07 UTC
If you do the following:

```
j = Job()
j2 = Job(j)
j2.id
```

there is no id specified. Don't know how long this has been the case but I'm guessing it will lead to bad things :(

**Comment by alexanderrichards** [comment] 2016-01-04 14:18
I assume that this is in the latest 6.1.14 that you see this? Do you also see it in 6.1.13?

**Comment by drmarkwslater** [comment] 2016-01-04 14:47
Just checked - this does indeed work properly in 6.1.13.

**Comment by rob-c** [comment] 2016-01-04 16:38
Examining the dictionary of the raw class reveals this (at some level) has worked as expected.
I suspect the id is incorrectly assigned by the jobregistry code.

e.g. the following contains what I expect
```
j2._impl.__dict__['id']
```

I'll look into the copy method (or '_impl' constructor in the Proxy as the 'cached' data doesn't appear to be updated as I'd expect)

**Comment by rob-c** [comment] 2016-01-04 20:28
I made a commit which alleviates but doesn't track down and fix this in a more correct way.
Basically the cache data is at some level being populated during job construction but not being updated during the object use.
This is the sort of thing I would prefer to avoid as part of #58 where we're having to keep track of the same data in 2 (or more) places rather than as a direct class attribute (behind a proxy or not).

I think it's worth tracking down where during the object construction that the index cache data is populated before the information seems to be available. I think this is probably caused by the initial flush which writes the job object to disk initially on creation.

As this particular issue is fixed I'm in favour of just moving on and testing 6.1.14 for release.

**Comment by rob-c** [comment] 2016-01-05 09:46
Rats, this fix appears to break the syntax:

```
j=Job(application=myApp())
```

The above line generates a Job object with an ```Executable``` binary which isn't expected. I'll do some digging and likely revert the above fix.

**Comment by milliams** [comment] 2016-01-05 10:12
Looking at develop at 2edb8cc I see that the `id` of `j2` is being copied into `j2.__dict__['id']` but not into `j2._data['id']`, probably due to some manual setting of values in the object's `__dict__`. This should be set in the `_data` dictionary since that is where the descriptor should be fetching it from.

**Comment by rob-c** [comment] 2016-01-05 10:30
@milliams This is the copy constructor which should not called in the above example. The line ```c.setNodeAttribute('id', c.id)``` explicitly is copying the 'id' value into the objects ```_data``` dictionary  not the ```__dict__```.
I forgot to remove this line after adding the ```_auto__init__``` to try and make sure that copied jobs are added to the dictionary, but I think in hindsight this is a bad idea due to the face we need copies behind the scenes which aren't auto-added to the repo.

The problem is that the ```._data['id']``` is being set to ```''``` and I'm trying to track down where this is being set (likely through a call to the JobRegistry from somewhere but I'm not certain)

**Comment by rob-c** [comment] 2016-01-05 14:39
OK, I've identified what was going on.
Due to a bug in the XML repo the information which should have been stored in ```_data``` was being stored incorrectly elsewhere when the object was loaded from disk.

How this allowed the job to get into a state where the id was defined as ```''``` I'm not 100% sure, however everything appears to be working in my local branch. I'll close this once I've uploaded the fix and testing suggests everything is OK

**Comment by rob-c** [comment] 2016-01-05 15:41
Hmm, spoke to soon. This can be condensed into the one line of:
```
j=Job(Job()); j.id
```
This shouldn't be failing but it correctly adds 2 jobs to the repo and fails to assign the 'id' stored in the ```_data``` to the second job. The jobs are added to the repo correctly and are handled by the repo logic just fine with this 'id' parameter missing (which seems to be a minor miracle that that code seems to stand up to this. But having a job with an id of ```''``` is at the very least extremely confusing.

I've put some fixes relating to other Job/repo bugs into github and I'll continue to look at this

**Closed** 2016-01-06 01:46 UTC
Labels: bug, Core

**Comment by rob-c** [comment] 2016-01-06 01:55
OK, this appears to have been caused by a fix for another problem that I was having. I'm going to have to start running more frequent tests to catch the likes of this. I was assigning the default value of non-copyable schema objects when performing a copyFrom which was called within a ```__construct__``` method within the proxy ```_init``` method.
I've changed the default behaviour to not overwrite attributes when the schema attribute is marked as non-copyable. Only if the schema attribute hasn't been populated is it populated with the default value.
