### ISSUE TITLE
Forbidden status transition for Local job

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#160] opened 2016-01-28 18:41 UTC
For a Local backend job I observed the error

```python
[19:37:56]
Ganga In [18]: j.submit()
Ganga.GPIDev.Lib.Job               : INFO     submitting job 1
Ganga.Lib.Executable               : INFO     Preparing Executable application.
Ganga.Lib.Executable               : INFO     Created shared directory: conf-c28e181b-a2ee-46e4-9231-33fe759853c7
Ganga.GPIDev.Lib.Job               : INFO     Preparing subjobs
Ganga.Lib.Executable               : INFO     Submitting a prepared application; taking any input files from conf-c28e181b-a2ee-46e4-9231-33fe759853c7
Ganga.GPIDev.Adapters              : WARNING  file /afs/cern.ch/user/u/uegede/gangadir/shared/uegede/conf-c28e181b-a2ee-46e4-9231-33fe759853c7/ganga-run is not executable, overriding executable permissions in the input sandbox
Ganga.GPIDev.Adapters              : INFO     submitting job 1 to Local backend
Ganga.GPIDev.Adapters              : ERROR    JobStatusError:  ('forbidden status transition of job 1 from "new" to "submitted"',)
Ganga.GPIDev.Lib.Job               : ERROR    JobManagerError: error during submit
Ganga.GPIDev.Lib.Job               : ERROR    JobManagerError: error during submit ... reverting job 1 to the new status
Ganga.Runtime.bootstrap            : ERROR    Error: JobError: Error: JobManagerError: error during submit
```
Trying to submit the job again it worked. I suspect some kind of race condition where the "submitting" state is missed.

Ulrik.

**Comment by rob-c** [comment] 2016-01-28 18:43
Hi Ulrik is this on the latest develop or 6.1.14? I think I saw this on 6.1.14 in the past.

**Comment by rob-c** [comment] 2016-01-29 14:15
@egede I'm unable to reproduce this on trunk despite submitting hundreds of jobs on multiple queues I think this is fixed in the latest develop.

**Comment by rob-c** [comment] 2016-02-05 14:27
I've not seen this in well over a week on develop. marking as closed for now

**Closed by rob-c** 2016-02-05 14:27 UTC
Labels: bug, Core
