### ISSUE TITLE
Merger problems reported by LHCb users

### ISSUE THREAD

**Issue by rob-c** [ganga-devs/ganga#766] opened 2016-09-05 07:42 UTC
Hi all,

An LHCb user has spotted that the job merger appears to be broken and I can confirm the error they see:
```
GangaAttributeError:  ('merger: attempt to assign an incompatible object <Ganga.Lib.Mergers.Merger.RootMerger object at 0x7f2cb0240410> to the property in category "mergers found cat: postprocessor"',)
```

I've had a look at the Merger tests and it appears we don't actually have a test which assigns a merger to a job and tests if it ran.

We should probably add this ASAP as this seems like a fairly big oversight.

I suspect this is likely related to the removal of ``___construct__`` but I'm surprised it's gone unreported for a few versions in this case. (Possibly due to summer).

I'll report back if a workaround if found,

Rob

**Comment by rob-c** [comment] 2016-09-05 07:47
And after looking this appears to be a different bug as the mergers should be hidden from the user. I'll see if running a post-processor is known to work.

**Comment by mesmith75** [comment] 2016-09-05 07:52
Yes, I thought this was supposed to be a postprocessor now?

**Comment by drmarkwslater** [comment] 2016-09-05 07:53
@rob-c The problem is from doing:
```
Job(merger = RootMerger())
```
as opposed to:
```
Job(postprocessors = RootMerger())
```
which works. So **technically** this isn't really a bug but it does mean very old backwards compatibility has been broken. I'm not sure if this is worth fixing or just telling users about it...

**Comment by rob-c** [comment] 2016-09-05 07:54
Yes in this case we shouldn't be allowing broken assignment or discovery by assignment from in front of the proxy.
The merger is no longer used  (it's only used in a proxy tool to convert objects to the postprocessor) so we shouldn't allow this.

This was reported against 6.2.0 for completness.

**Comment by drmarkwslater** [comment] 2016-09-05 07:55
Rightio - closing 😄

**Closed by drmarkwslater** 2016-09-05 07:55 UTC
Labels: bug, Core

**Comment by rob-c** [comment] 2016-09-05 07:57
Hmm, I see what you mean @drmarkwslater I'm wondering if we can be expected to fix this as this behaviour is currently needed for loading job objects from disk...

Could we add a specific kwd argument to turn off the assignment protection when loading a job and turn this back on when a user creates an object from in front of the GPI?

**Comment by drmarkwslater** [comment] 2016-09-05 08:03
I would personally say this is not worth it anymore as mergers were retired in early 2013 (Feb or May depending on where you look) and so I doubt people will still have jobs they're likely to go back to from that time now. If they do, then maybe we can revisit it but otherwise it would add code/dev time to something that will probably will never be needed and hasn't even been picked up until now.

**Comment by rob-c** [comment] 2016-09-05 08:05
You're probably correct. We should probably be adding some step into the Job setter to migrate this but this should have been done back then. Given this is potentially 3 years old I think it's probably ok to mark this as won't fix.
